### ISSUE TITLE
NOF7 Documentation bug: CustomerRepository will not compile

### ISSUE THREAD

**Issue by tedneward** [NakedObjectsGroup/NakedObjectsFramework#10]
In the section "Writing your first Naked Objects application", the sample code for CustomerRepository will not compile as written.

Look at the line "public Customer CreateNew Customer()". Presumably this has a space in CreateNewCustomer, but for a simple starting guide this should be corrected.

**Comment by richardpawson** [comment]
Thanks  -  will correct, and issue a complete working example, per other comment.
