### ISSUE TITLE
downloading fileattachment with an action does not work anymore

### ISSUE THREAD

**Issue by smiltenburg** [NakedObjectsGroup/NakedObjectsFramework#100]
In NOF7 we used an action on our "file" class to download the file. 
This does not work anymore in NOF9.

I'm not sure if this is deliberate or a bug

I think the new way is better because it takes less clicks to get to your file. (If I get it to work).

**Comment by richardpawson** [comment]
Thanks for reporting.  I can confirm that the first example in the manual (handling Byte[] directly) does not now work, but the second example (using FileAttachment) does.  I think that is what you were saying also.

I am not sure from memory alone whether the 1st option was deliberately dropped or not.  I will investigate and either report this as a bug, or if there was a reason why we could not the 1st way to work in NOF9, will update the Manual.

**Comment by richardpawson** [comment]
Actually, I'm a bit confused by your two posts as to what is and what is not working for you.  Could you close the other one and clarify on this thread?

**Comment by smiltenburg** [comment]
Hi Richard, 
This issue was to tell you that something that was working in NOF7 now does not seem supported anymore (downloading from an action)

The other issue is to tell you that the "basic" implementation like described in the manual does not work and the manual needs to be updated or it needs to be fixed (I am NOT using this basic implementation in my project). To be clear I also confirm the second example described in the manual works.

What I'm struggling with is to get the implementation we had for our NOF7 project which uploaded/downloaded the file from azure blob storage with an action working with the new "property" way of downloading a file. Since this is not documented functionality I'm still trying to get this to work on my own. Will get back to you with another "issue" if I can't get it to work.

**Comment by richardpawson** [comment]
Can you clarify what you mean by 'downloading from an action' please  -  e.g. by a code snippet.

**Comment by smiltenburg** [comment]
Hi Richard, 
What I mean by downloading from an action is the following:

`public FileAttachment DownloadAttachment()
{
        if (AttContent == null) return null;
        return new FileAttachment(AttContent, AttName, AttMime) { DispositionType = "inline" };
}
`

**Comment by richardpawson** [comment]
I have updated the documentation in regard to FileAttachments and Images.  Please note that it is correct that NOF9 does not support actions that return FileAttachment  -  only properties  -  because FileAttachment is not a recognised (standalone) Restful Objects representation.
