### ISSUE TITLE
file download in chrome bug

### ISSUE THREAD

**Issue by smiltenburg** [NakedObjectsGroup/NakedObjectsFramework#102]
Hi, last couple of days I have been struggling with getting my download code to work from NOF7 to NOF9. Today I checked to see how the behavior was in IE, and noticed all my problems where gone!
So my problems seem to be (partially) chrome specific.

I have an object which has multiple files attached (see below for class spec)
With my current code I get the following results:

**On CHROME:**
- .pdf file uploads ok, download seems to trigger a new tab to open and immediately close (no file is downloaded
- .txt file: uploads ok, download seems to trigger a new tab to open and immediately close (no file is downloaded
- .doc file: uploads ok, file downloads as random guid+extension 

**On IE** 
- all file types are downloaded ok (with correct filename given to the returned FileAttachment object)

`       public class File
       {
        public IDomainObjectContainer Container { set; protected get; }

        [Hidden(WhenTo.Always)]
        public void Initialize(FileAttachment fileAttachment, BestandsType fileType)
        {
            if (Id == Guid.Empty)
            {
                Id = Guid.NewGuid();
            }
            FileType = fileType;
            MimeType = fileAttachment.MimeType;
            UploadItem(fileAttachment);
        }

        [NakedObjectsIgnore]
        public virtual Guid Id { get; set; }

        public virtual BestandsType FileType { get; set; }

        [NakedObjectsIgnore]
        [Required]
        public virtual string FileLocation { get; set; } //todo deze kan straks weg

        [Required]
        public virtual string FileName { get; set; }

        private byte[] fileBytes;

        public virtual FileAttachment Attachment
        {
            get
            {
                try
                {
                    if (fileBytes==null)
                    {
                        var storageConnectionString = CloudConfigurationManager.GetSetting("StorageConnectionString");
                        CloudStorageAccount storageAccount = CloudStorageAccount.Parse(storageConnectionString);
                        CloudBlobClient client = storageAccount.CreateCloudBlobClient();
                        CloudBlobContainer container = client.GetContainerReference("documentcontainer");
                        CloudBlockBlob blob = container.GetBlockBlobReference(Id.ToString().ToLower());

                        blob.FetchAttributes();
                        if (blob.Properties.Length == -1)
                        {
                            //hmm something went wrong during upload
                            return null;
                        }
                        fileBytes = new byte[blob.Properties.Length];
                        blob.DownloadToByteArray(fileBytes, 0);
                    }

                    var attachment = new FileAttachment(fileBytes, FileName, MimeType);
                    return attachment;
                }
                catch (Exception e)
                {
                    Container.RaiseError($"Error downloading: {e}");
                    return null;
                }
            }
        }

        [NakedObjectsIgnore]
        public virtual string MimeType { get; set; }

        protected void UploadItem(FileAttachment fileAttachment)
        {
            try
            {
                var file = fileAttachment.GetResourceAsByteArray();
                CloudStorageAccount storageAccount = CloudStorageAccount.Parse(CloudConfigurationManager.GetSetting("StorageConnectionString"));
                CloudBlobClient client = storageAccount.CreateCloudBlobClient();
                CloudBlobContainer container = client.GetContainerReference("documentcontainer");
                CloudBlockBlob blob = container.GetBlockBlobReference(Id.ToString().ToLower());
                blob.UploadFromByteArray(file, 0, file.Length);
                FileName = fileAttachment.Name;
                FileLocation = "dummy, not used anymore in NOF9";
            }
            catch (Exception e)
            {
                Container.RaiseError($"Error uploading:{e}");
            }
        }

        public string VerwijderFile()
        {
           
            Container.DisposeInstance(this);
            return "File is verwijderd";
        }

        public override string ToString()
        {
            return FileName;
        }
    }`

**Comment by richardpawson** [comment]
We will look into this.  Downloading a file via an action (separate post) is never going to work, because there is no Restful Objects representation for File, but it should work correctly as a property that you can click on  -  for both IE and Chrome.

**Comment by smiltenburg** [comment]
hmm apparently my chrome extension "adblock" prevented me from downloading certain files.
Turning this extension off made downloading the files work again in chrome.

adding the following rule to adblock also worked: 
@@http://localhost$document

However, the powerpoint and word documents still download as "random guid.docx" instead of "filename.docx".
So downloading the same file again and again results in a different filename on disk.
This while the file name property passed to the FileAttachment object being returned is correct ("filename.docx"). Do you also see this behaviour?? When downloading this same file in Internet Explorer the random guid naming does NOT occur and the file gets downloaded with the correct filename. 

FYI this time I tested this with ALL my extensions turned off. ;)

**Comment by richardpawson** [comment]
I can confirm that we get the same behaviour as you in Chrome (i.e. random guid) and also in Firefox, but not in IE, which gets the file name correct.  So the file name is definitely coming down the wire; I'm not sure why Chrome/Firefox is doing that.

**Comment by richardpawson** [comment]
I can confirm that I see the the same behaviour (random naming of files downloaded) in Chrome but IE works fine.  And the filename is being returned correctly in the Http response, so I am not sure why Chrome does that.  A quick search suggests that we're not the only ones who've seen something like this e.g. https://productforums.google.com/forum/#!topic/chrome/FzsWGtxyQl4
