### ISSUE TITLE
Property hidden 'UntilPersisted' not showing after saving, until reload

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#104]
To reproduce this, mark a property with Hidden(WhenTo.UntilPersisted).  Create a transient object of this type (property, correctly, does not show), complete other fields and save.  Property still does not show, until you Reload it.

Looking at the Http traffic, it is clear that this is a server-side issue: the returned RO representation does not have the property either, initially.

**Comment by scascarini** [comment]
Client and server side fixes made.

**Comment by scascarini** [comment]
Test added and OK
