### ISSUE TITLE
github link to download manual is broken?

### ISSUE THREAD

**Issue by smiltenburg** [NakedObjectsGroup/NakedObjectsFramework#105]
It seems to point to an old version (I seem to have downloaded a newer version a while ago)

this is the current link:
https://github.com/NakedObjectsGroup/NakedObjectsFramework/blob/6aadec10146d007067baeeeb302fb135c869d3b8/Documentation/DeveloperManual.docx?raw=true

and the doc file I downloaded earlier had a picture and a "last updated on" on page 1.

**Comment by richardpawson** [comment]
I'm not sure where you got that link from?  The link on the ReadMe for the NO9 manual is: https://github.com/NakedObjectsGroup/NakedObjectsFramework/blob/master/Documentation/NOF9DeveloperManual.docx?raw=true and this is working.

(I checking it I discovered that the link to the NOF8 manual was broken - though this still wasn't the link you have included  -  and I have now removed that as NOF8 is superseded.)

**Comment by smiltenburg** [comment]
i got it from the only wiki page (at the bottom)
https://github.com/NakedObjectsGroup/NakedObjectsFramework/wiki

**Comment by richardpawson** [comment]
OK, thanks  -  now fixed.
