### ISSUE TITLE
Attribute-based Authorization with Auth0

### ISSUE THREAD

**Issue by smiltenburg** [NakedObjectsGroup/NakedObjectsFramework#106]
Hi guys, it's me again, sorry :s

In the manual it says there are two options for Authorization:
- Attribute based authorization
- Custom Authorization

Our NOF7 application used Attribute-based Authorization with a custom controller in the webclient project which allowed logging in with google and storing/setting roles with the Aspnet.identity.UserManager.

After my migration to NOF9 I am searching for a way to get this role-based access working again. We only have 3 roles in our application: Guest / Office / Admin.

The manual speaks of defining the attributes but not how to fill the Roles collection of a user in context with the now default option of Auth0.
It references ASP.NET which I think is outdated since NOF9 now uses angular.

I tried the Auth0 sample rule "set roles to a user" to set the rules to my user object returned from Auth0 
and I can verify that my user object gets the role "Admin" set.

app_metadata: { roles: [ 'Admin' ] },
      roles: [ 'Admin' ],

This however does not seem to get picked up by the NOF.

Am I exploring a wrong path here?

I also tried to implement the custom authorization but the IsEditable and IsVisible methods of both my DefaultAuthorizer as my NamespaceAuthorizer did not get touched after registrating them on the Unityconfig.Registertypes as described in the manual like so:

`container.RegisterInstance<IAuthorizationConfiguration>(NakedObjectsRunSettings.AuthorizationConfig(), new ContainerControlledLifetimeManager());`

code from the NakedObjectsRunSettings

`

        public static IAuthorizationConfiguration AuthorizationConfig()
        {
            var config = new AuthorizationConfiguration<MyDefaultAuthorizer>();
            config.AddNamespaceAuthorizer<MyNamespaceAuthorizer>("SogyoTracker.DomeinModel");
            return config;
        }

        public class MyDefaultAuthorizer : ITypeAuthorizer<Object>, INamespaceAuthorizer
        {
            public bool IsEditable(IPrincipal principal, object target, string memberName)
            {
                throw new NotImplementedException();
            }

            public bool IsVisible(IPrincipal principal, object target, string memberName)
            {
                throw new NotImplementedException();
            }
        }

        public class MyNamespaceAuthorizer : INamespaceAuthorizer
        {
            public bool IsEditable(IPrincipal principal, object target, string memberName)
            {
                throw new NotImplementedException();
            }

            public bool IsVisible(IPrincipal principal, object target, string memberName)
            {
                throw new NotImplementedException();
            }
        }`

not sure how to proceed from here

**Comment by richardpawson** [comment]
I am not sure if we have ever tested role-specific attribute-based authorization when working with Auth0 authentication in NOF9, but I have tested the custom authorization approach.  

Just to check -  did you register the type of the facet decorator as well as the instance of IAuthorizationConfiguration, per the manual:

```
container.RegisterType(typeof(IFacetDecorator), typeof(AuthorizationManager), 
           "AuthorizationManager", new ContainerControlledLifetimeManager());
container.RegisterInstance(typeof(IAuthorizationConfiguration), 
            NakedObjectsRunSettings.AuthorizationConfig(), new ContainerControlledLifetimeManager());
```

I ask because your posting shows only the RegisterInstance call.

**Comment by smiltenburg** [comment]
I indeed forgot to add the IFacetDecorator and now i'm coming in the IsVisible method. 
Thx for noticing!
