### ISSUE TITLE
Download FileAttachment from TableView

### ISSUE THREAD

**Issue by smiltenburg** [NakedObjectsGroup/NakedObjectsFramework#107]
I would like to request the following feature:

If an class, for instance Person, has a list of Files
`public virtual ICollection<File> Files { get; set; } = new List<File>();`

And the file class contains a property of type FileAttachment

And the file list is annotated with [TableView(true, "FileType", "Attachment")]
(with the FileAttachment property being named "Attachment")

That the column "Attachment" of the tableview of the files on the object Person is clickable and also downloads/opens the file.

This would speed up the downloading process so you don't have to open the "file" entity to download it.

**Comment by richardpawson** [comment]
I think this is a fair request, and consistent with our general thinking.  I'll mark it as an enhancement, but I can't schedule it yet.

**Comment by richardpawson** [comment]
This could be implemented as a customisation.
