### ISSUE TITLE
Value does not get rendered because it does not occur in Choices 

### ISSUE THREAD

**Issue by smiltenburg** [NakedObjectsGroup/NakedObjectsFramework#110]
I have the following situation:
- when a new object of class A is added by the user, I'm adding a ContactMoment object to it's property collection by code (in the 'persisted' method of class A). To indicate to the user this instance was added automatically I add it with the enum value "Medium.Automatic". Since I do not want users to be able to select this "automatic" value, I removed it from the list in the UI by implementing the "ChoicesMedium" method on the ContactMoment class which holds the Medium (ENUM) property.
This however also seems to affect the ability for the value of the property (Medium.Automatic) to be rendered in the tableview, something I was not expecting.
And another thing is that it is not rendered when editing the object ContactMoment itself.

So the database holds the value "automatic" but is is not shown to the user in both the view as edit mode.

I understand that the situation where in the UI you need to be able to edit a property value which you are not able to select is "troublesome" and can have different flavors of implementation, but not letting the user view the value seems like a bug.

So to be clear:

I have a class ContactMoment with a property Medium (ENUM)
I have a class A with a property of type list<ContactMoment> which is annotated to display as a tableview

[TableView(true, nameof(ContactMoment.Medium))]
public virtual ICollection<ContactMoment> ContactMomenten {get;set;}

The tableview renders the column "Medium" but not with any values which are not included in the ChoicesMedium method on the ContactMoment class

For now my workaround is to just show the user the "automatic" option and persuade them not to use it.

**Comment by richardpawson** [comment]
I have not come across this before, but then I don't think I've ever tried to filter-down an enum, using Choices.  Note that it is not just in the table view where it doesn't render the 'restricted' value  -  even as a property in object view.

I'm not going to record this as a bug  -  it may just be a limitation.  I imagine that using Choices with an Enum property is causing NOF to get confused between two different capabilities.  So I suggest that you need to work-around this by either:

1. Allow Automatic to be rendered in the user's drop-down, but use a Validate method to prevent them from actually saving that option.

2. Disable the field and only allow it to be altered via an action.  Filtering the list of Enum options on the action parameter should not be a problem.

3. Replace the enum with a simple look-up class i.e. an associated object.
