### ISSUE TITLE
multiline effect for edit mode and TableView

### ISSUE THREAD

**Issue by ROIInstitute** [NakedObjectsGroup/NakedObjectsFramework#111]
Hi,

When I add MultiLine to a text property this property is rendered with the amount of lines specified in the "read" view of the object.
1) It would be nice if it would only expand to the level that there is actually text in this field (how many lines) as not to waste screen real estate.

In edit mode this results in a manually expandable textarea.
2) It would be nice if in edit mode the height of the textarea would also be set according to the value of MultiLine.

3) In the TableView the Multiline annotation could be taken into account for the rendering of the table.

**Comment by smiltenburg** [comment]
sorry.. opened this issue under a wrong account. I closed it and reopened it under my own account
