### ISSUE TITLE
My next / last button does not work - on a very complex query

### ISSUE THREAD

**Issue by smiltenburg** [NakedObjectsGroup/NakedObjectsFramework#113]
Hi, 

When I use an action to query my objects on different fields and return the results as an IQueryable, I get a paged result.

When I click next the navigation to the next page fails due to an internal server error.
This does not happen on actions with less filter fields.

So I guess this has something to do with amount of filter fields in the query and the resulting url,the url the applications wants to navigate to is 2641 characters long. 
Maybe it's not the length, since the initial query (page 1) completes successfully and is also 2641 characters long.

hmm when i decode the url the buildup of the url seems quite different:

working (decoded) url:

http://localhost:5001/gemini/list?m1=KandidaatRepository&a1=ZoekEenKandidaat&pg1=1&ps1=20&s1_=0&c1=Table&pm1_KandidaatType=0&pm1_Voornaam=""&pm1_Tussenvoegsel=""&pm1_Achternaam=""&pm1_TelefoonNummerOfMobiel=""&pm1_HoogstGenotenOpleiding=[{"wrapped":{"wrapped":{"wrapped":1},"repTypeToModel":{}}},{"wrapped":{"wrapped":{"wrapped":2},"repTypeToModel":{}}},{"wrapped":{"wrapped":{"wrapped":8},"repTypeToModel":{}}},{"wrapped":{"wrapped":{"wrapped":10},"repTypeToModel":{}}},{"wrapped":{"wrapped":{"wrapped":7},"repTypeToModel":{}}},{"wrapped":{"wrapped":{"wrapped":3},"repTypeToModel":{}}},{"wrapped":{"wrapped":{"wrapped":6},"repTypeToModel":{}}},{"wrapped":{"wrapped":{"wrapped":0},"repTypeToModel":{}}},{"wrapped":{"wrapped":{"wrapped":4},"repTypeToModel":{}}},{"wrapped":{"wrapped":{"wrapped":5},"repTypeToModel":{}}},{"wrapped":{"wrapped":{"wrapped":9},"repTypeToModel":{}}},{"wrapped":{"wrapped":{"wrapped":11},"repTypeToModel":{}}}]&pm1_statussen=[{"wrapped":{"wrapped":{"wrapped":9},"repTypeToModel":{}}},{"wrapped":{"wrapped":{"wrapped":8},"repTypeToModel":{}}},{"wrapped":{"wrapped":{"wrapped":3},"repTypeToModel":{}}},{"wrapped":{"wrapped":{"wrapped":5},"repTypeToModel":{}}},{"wrapped":{"wrapped":{"wrapped":0},"repTypeToModel":{}}},{"wrapped":{"wrapped":{"wrapped":1},"repTypeToModel":{}}},{"wrapped":{"wrapped":{"wrapped":6},"repTypeToModel":{}}},{"wrapped":{"wrapped":{"wrapped":10},"repTypeToModel":{}}},{"wrapped":{"wrapped":{"wrapped":4},"repTypeToModel":{}}},{"wrapped":{"wrapped":{"wrapped":13},"repTypeToModel":{}}},{"wrapped":{"wrapped":{"wrapped":7},"repTypeToModel":{}}},{"wrapped":{"wrapped":{"wrapped":12},"repTypeToModel":{}}},{"wrapped":{"wrapped":{"wrapped":11},"repTypeToModel":{}}}]&pm1_startTijd=""&pm1_eindTijd=""&pm1_inclusiefReedsMedewerker=true&pm1_inclusiefReedsStagiair=true

The "next page" url (decoded) that does not work:
http://localhost:5000/services/SogyoTracker.DomeinModel.Repositories.KandidaatRepository/actions/ZoekEenKandidaat/invoke?{"KandidaatType":{"value":0},"Voornaam":{"value":""},"Tussenvoegsel":{"value":""},"Achternaam":{"value":""},"TelefoonNummerOfMobiel":{"value":""},"HoogstGenotenOpleiding":{"value":[{"href":"function () { var t = this.link(); return t ? t.href() : null }"},{"href":"function () { var t = this.link(); return t ? t.href() : null }"},{"href":"function () { var t = this.link(); return t ? t.href() : null }"},{"href":"function () { var t = this.link(); return t ? t.href() : null }"},{"href":"function () { var t = this.link(); return t ? t.href() : null }"},{"href":"function () { var t = this.link(); return t ? t.href() : null }"},{"href":"function () { var t = this.link(); return t ? t.href() : null }"},{"href":"function () { var t = this.link(); return t ? t.href() : null }"},{"href":"function () { var t = this.link(); return t ? t.href() : null }"},{"href":"function () { var t = this.link(); return t ? t.href() : null }"},{"href":"function () { var t = this.link(); return t ? t.href() : null }"},{"href":"function () { var t = this.link(); return t ? t.href() : null }"}]},"statussen":{"value":[{"href":"function () { var t = this.link(); return t ? t.href() : null }"},{"href":"function () { var t = this.link(); return t ? t.href() : null }"},{"href":"function () { var t = this.link(); return t ? t.href() : null }"},{"href":"function () { var t = this.link(); return t ? t.href() : null }"},{"href":"function () { var t = this.link(); return t ? t.href() : null }"},{"href":"function () { var t = this.link(); return t ? t.href() : null }"},{"href":"function () { var t = this.link(); return t ? t.href() : null }"},{"href":"function () { var t = this.link(); return t ? t.href() : null }"},{"href":"function () { var t = this.link(); return t ? t.href() : null }"},{"href":"function () { var t = this.link(); return t ? t.href() : null }"},{"href":"function () { var t = this.link(); return t ? t.href() : null }"},{"href":"function () { var t = this.link(); return t ? t.href() : null }"},{"href":"function () { var t = this.link(); return t ? t.href() : null }"}]},"startTijd":{"value":""},"eindTijd":{"value":""},"inclusiefReedsMedewerker":{"value":true},"inclusiefReedsStagiair":{"value":true},"x-ro-page":2,"x-ro-pageSize":40,"x-ro-inline-collection-items":true}

**Comment by richardpawson** [comment]
Without looking at this in detail, it could be that with such a complex query you are hitting the Url limit enforced by your browser and/or server. (Certainly I have seen this as an issue in the past).  You should be able to change the limit  -  but that's in your browser/server settings, not NOF.

You might also want to think about whether you should be reducing the  complexity of this querying  -  by breaking up the main types of query into separate actions, and then letting the user vary just a few parameters within each action?

**Comment by smiltenburg** [comment]
Hi Richard, 
I understand that limiting the amount of fields that get communicated can fix this issue.

But in my situation I have pending requests from users to have even more fields to filter on.
Their use case might be called "the poor man's reporting tool".

I understand this situation might not be a usecase you would be willing to support.

But looking at the produced url I think the url can be made less verbose and therefore shorter (and more readable?).

**Comment by richardpawson** [comment]
Have you tried using the in-built mechanism for shortening URLs? If not  look up 'Shortening Urls' in the manual. You could possibly use it to tokenize any commonly-repeated words/character sequences in the Url

**Comment by richardpawson** [comment]
Please also note:  I don't think you've realised that you are looking at two entirely different types of Url.  The ones (in your case) beginning localhost:5001 are the client Urls  -  these exist only within the client, effectively encoding the state of the display. They are not sent to the server and do not represent server side resources.

The ones beginning localhost:5001 are the Urls that the client generates for an http communication to the server  -  and their format corresponds to the Restful Objects specification.  These are never displayed in the browser's address bar  -  they are invisible to the user.   

The two are not formally related.

**Comment by smiltenburg** [comment]
Hi,
My problem seems to be in the Rest request going to backend (these are getting a 500 internal server error, and not an error regarding url length ([https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/requestfiltering/requestlimits/]). 
So the url shortening you suggested, which the manual states is for client side only, won't work.

What I am curious about is why when I filter on no specific fields (resulting in a query server side with (almost) no parameters for sql)

I get a bit of json encoded in the url which looks like (taken from url above)

```
{
  "KandidaatType": { "value": 0 },
  "Voornaam": { "value": "" },
  "Tussenvoegsel": { "value": "" },
  "Achternaam": { "value": "" },
  "TelefoonNummerOfMobiel": { "value": "" },
  "HoogstGenotenOpleiding": {
    "value": [
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" },
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" },
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" },
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" },
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" },
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" },
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" },
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" },
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" },
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" },
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" },
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" }
    ]
  },
  "statussen": {
    "value": [
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" },
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" },
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" },
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" },
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" },
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" },
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" },
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" },
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" },
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" },
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" },
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" },
      { "href": "function () { var t = this.link(); return t ? t.href() : null }" }
    ]
  },
  "startTijd": { "value": "" },
  "eindTijd": { "value": "" },
  "inclusiefReedsMedewerker": { "value": true },
  "inclusiefReedsStagiair": { "value": true },
  "x-ro-page": 2,
  "x-ro-pageSize": 40,
  "x-ro-inline-collection-items": true
}
```

What suprises me here are all the entries 
`{ "href": "function () { var t = this.link(); return t ? t.href() : null }" } `
which seem to be communicating the (default) selected enum values to filter on for this field. 
Not only does it seem unnecessarily verbose, they also do not seem to hold any info as to "which" enum value is selected.

Further investigating results in another error scenario.
This is when the "default selection" of the two enum fields "HoogstGenotenOpleiding" and "statussen" is overridden (selecting one enum value instead of all of the available values (default selection)).
So this happens when the results are queried for the first time (before pressing "next / last")
I can hit the breakpoint in the repository and it seems to return an IQueryable just fine.

In the nakedobjectslog.txt i find a warning that could be related:

2017-10-02 09:42:32,174 WARN 18 NakedObjects.Meta.Facet.ActionInvocationFacetViaMethod - Invoking action via reflection as no delegate ServiceSpecImmutable for KandidaatRepository.System.Linq.IQueryable`1[SogyoTracker.DomeinModel.Kandidaat] ZoekEenKandidaat(SogyoTracker.DomeinModel.Enums.KandidaatType, System.String, System.String, System.String, System.String, System.Collections.Generic.IEnumerable`1[SogyoTracker.DomeinModel.Enums.StudieNiveau], System.Collections.Generic.IEnumerable`1[SogyoTracker.DomeinModel.Enums.KandidaatStatus], System.DateTime, System.DateTime, Boolean, Boolean)

**Comment by smiltenburg** [comment]
When I remove the enum fields for the action the problem goes away. This could be because the url becomes much shorter, or maybe because something is wrong with searching on enums.

for reference my code:
`public IQueryable<Kandidaat> ZoekEenKandidaat(
                    KandidaatType KandidaatType,
                    [Optionally] string Voornaam,
                    [Optionally]string Tussenvoegsel,
                    [Optionally] string Achternaam,
                    [Optionally]string TelefoonNummerOfMobiel,
                    [Optionally] IEnumerable<StudieNiveau> HoogstGenotenOpleiding,
                    [Optionally] IEnumerable<KandidaatStatus> statussen,
                    [Mask("d")] [Optionally] DateTime startTijd,
                    [Mask("d")] [Optionally] DateTime eindTijd,
                    bool inclusiefReedsMedewerker,
                    bool inclusiefReedsStagiair)
        {

 public IEnumerable<StudieNiveau> Default5ZoekEenKandidaat()
        {
            var list = new List<StudieNiveau>
            {
                StudieNiveau.Onbekend,
                StudieNiveau.Basisschool,
                StudieNiveau.VMBO,
                StudieNiveau.Havo,
                StudieNiveau.VWO,
                StudieNiveau.MBO,
                StudieNiveau.HBO_AD,
                StudieNiveau.Bachelor_HBO,
                StudieNiveau.Bachelor_WO,
                StudieNiveau.Master,
                StudieNiveau.PHD,
                StudieNiveau.Post_Doc
            };
            return list;
        }
`

A little more investigating:
From all my actions where they return an iqueryable and the arguments contain a List of enums the "next page"  button request fails. (even with less fields to filter on)

So its seems there is some bug related to using an enum list as argument for an IQueryable action.

**Comment by richardpawson** [comment]
NOF is not designed to recognise IEnumerable, only IEnumerable<T> where T is an acceptable type.  

And  I don't know for sure, but, per your other thread, if T is itself an Enum that might cause confusion.  Just try that first IEnumerable<StudieNiveau>.

Failing that I suggest converting those enum values into strings, and making the parameter type a string and choices returning an IEnumerable<string>. You can easily parse that back into the enum value inside the method.

**Comment by smiltenburg** [comment]
hmm this is weird... the github texteditor uses markdown and removes everything in my codeblock between the < and > characters.. 
it is most definately there in my comment when editing it but is not shown in view mode...

so the I return an IEnumerable of type StudieNiveau (which is an enum)

**Comment by richardpawson** [comment]
FYI (if this is still an issue) what I meant was as follows (my changes indicated in comments):

`public IQueryable<Kandidaat> ZoekEenKandidaat(
                    KandidaatType KandidaatType,
                    [Optionally] string Voornaam,
                    [Optionally] string Tussenvoegsel,
                    [Optionally] string Achternaam,
                    [Optionally] string TelefoonNummerOfMobiel,
                    [Optionally] string hoogstGenotenOpleiding, //Just string, not IEnumerable<string>. It is the choices method that makes is a drop-down
                    [Optionally] string statussen,
                    [Mask("d")] [Optionally] DateTime startTijd,
                    [Mask("d")] [Optionally] DateTime eindTijd,
                    bool inclusiefReedsMedewerker,
                    bool inclusiefReedsStagiair)
        {

public IEnumerable<string> Choices5ZoekEenKandidaat()  //Choices, not Default (though can also have a Default method)
        {
            var list = new List<string>
            {
                StudieNiveau.Onbekend.ToString(),
                StudieNiveau.Basisschool.ToString(),
                StudieNiveau.VMBO.ToString(),
                StudieNiveau.Havo.ToString(),
                StudieNiveau.VWO.ToString(),
                StudieNiveau.MBO.ToString(),
                StudieNiveau.HBO_AD.ToString(),
                StudieNiveau.Bachelor_HBO.ToString(),
                StudieNiveau.Bachelor_WO.ToString(),
                StudieNiveau.Master.ToString(),
                StudieNiveau.PHD.ToString(),
                StudieNiveau.Post_Doc.ToString()
            };
            return list;
        }`

**Comment by smiltenburg** [comment]
Hi Richard.. 
Your suggestion resolves the issue of the error when moving to the next result page, but the functionality becomes different.

I get a dropdown to choose 1 value instead of having a listbox where the user can select multiple values. 

I would like to provide my users with the possibility of selecting more than one enum value to filter on so this is not really a solution for me.

What is curious to me is why the server would be able to handle the first request with no problems, and when what I believe all the "next page" url should do is add a "skip x" would suddenly fail.

But maybe the problem lies in the difference of how a form post is handled compared to the "next page" get_url.
