### ISSUE TITLE
Download Report (IQueryResult)

### ISSUE THREAD

**Issue by smiltenburg** [NakedObjectsGroup/NakedObjectsFramework#114]
As a follow up on the "poor mans reporting tool" my user would like to download the data of their search result as an csv / excel so they can do further filtering / reporting on the data there.

To my knowledge:
- you can create a query-result-contributed action but this action only receives the data from the current page of the resultset as input (and I want all results).
- you can not download a file directly from an action

So I thought about it and came up with this workaround:
- create an action which uses the same logic. 
- but this method also create a "report" with a FileAttachment property and uploads the in-memory generated csv in cloudstorage (or somewehere else). 
- afterwards the user would search for the latest generated report and download it through the fileattachement property. 

Is this the way you would go about doing this?

**Comment by richardpawson** [comment]
Sounds fine to me  -  name the file by user name and timestamp, presumably.  Or just username and overwrite it each time.  

(As well as the paging issue, collection-contributed action would also be a very expensive way to do it).

But another option to consider:  you can't return a FileAttachment directly from an action, but an action could return an object containing a file attachment (possibly a view model, I'm not certain).  One more click for the user, but not much.
