### ISSUE TITLE
navigation problem with moving back through the "create/edit" view

### ISSUE THREAD

**Issue by smiltenburg** [NakedObjectsGroup/NakedObjectsFramework#117]
Currently there is a "save and close" button for unsaved entities.
This button is not available when you are editing an already saved entity.

The flow to currently move through the application to edit something is:
- open parent entity
- click on child entity
- click on edit
- perform edit
- click save (I am redirected to the child entity)
- click back (now I am redirected to the "edit page" again **This is unwanted**)
- click back again (no I am redirected to the parent entity)

There is a step here that could be removed.
This problem is also present when using the "save and close" button like when saving an not yet persisted entity)

**Comment by richardpawson** [comment]
Now that the Client is mult-layered to facilitate customisation, this could be implemented as a customisation.
