### ISSUE TITLE
NOF8 Documentation issue: Template cannot reach localhost server

### ISSUE THREAD

**Issue by tedneward** [NakedObjectsGroup/NakedObjectsFramework#12]
Reproduction:

- Download template .zip as listed in DeveloperManual
- Unzip into "NOF8TemplateApp" directory
- Open Template.sln in VS2015 Community Edition
- Run (Google Chrome, latest)
- ASP.NET Output in VS Output Console appears normal (no errors listed)
- "Loading menus" appears in browser tab
- After 60 - 75 secs, 500 error returned

**Comment by tedneward** [comment]
OK, from looking at the template's browser activity, it's trying to request "http://localhost:59949/rest", which I find odd--if it's making an HTTP API call, then I would've expected it to be requesting some endpoint, but I'm new to this, so....

BTW, when doing a curl from the command-line, it times out, unless I do "curl -v ...", in which case it simply returns a 500. I'm not trying to get all the x-ro-* headers correct, so perhaps that's part of the problem, but unfortunately there's no stack traces anywhere, so it's hard to know what I got wrong with the Template out of the box.

**Comment by richardpawson** [comment]
I think that this is failing to create the database.

**Comment by richardpawson** [comment]
Ted, please see this thread  -  Ury had the same issue and I have had it myself:

https://github.com/NakedObjectsGroup/NakedObjectsFramework/issues/4 

We are trying hard to provide a clearer message when this happens, but it seems to be outside our control, and the behaviour of VS2015 in this regard is very unhelpful.

**Comment by tedneward** [comment]
OK, I'll read through that and see what I can find.

Perhaps it might be an easier approach if LocalDb is used by default? I think that's what's available out of the box in VS2015, but to be honest I lose track. I'll ping a few folks I know on the VS team and/or MVP community and see if there's a definitive answer to that.

**Comment by richardpawson** [comment]
BTW the call to http://localhost:59949/rest is correct  -  this call should default to the Restful Objects Home resource and thereafter the client will make calls to more specific RO resources.  The problem you are experiencing is, I think,  that the servers doesn't exist because the database wasn't created.

In the previous version (which Ury had tried) I had no connection string - so VS used localDb by default, but that was no better.  If it works for you changing the connection string to LocalDb, please let me know.

**Comment by tedneward** [comment]
Richard: Try this, tell me if it works for you?

  <connectionStrings>
    
    <add name="NakedObjectsExample"
         connectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Example.mdf;Initial Catalog=NakedObjectsExample;Integrated Security=True;MultipleActiveResultSets=True"
         providerName="System.Data.SqlClient" />
  </connectionStrings>

I think this works with the LocalDB settings of whatever version of LocalDB happens to be installed. It seems to work with VS2015, though I did create an "Example.mdf" file (right-click the NakedObjects.Template project node, select Add...|SQLServer Database, and type in "Example") along the way, and I'm not sure if Example.mdf is required or not. (If you create it, change its properties to also Copy to Output Directory = "Copy always".)

That's what's working for me at this exact moment. I think that switching over to LocalDB is going to be more "install-portable" across different VS 2015 installs.

Might also want to mention this somewhere in the dev guide, at least until there's reasonable proof that it works across multiple environments.

**Comment by richardpawson** [comment]
Thanks, Ted, I will try that out tomorrow.  And thanks for your patience.  We really are determined to get back to the 'easy start' example for NOF8. And will add a troubleshooting help ...

**Comment by tedneward** [comment]
LocalDB "should" always be installed, and I'm trying to make sure that the above connection string will "always" work out of the box (at least for VS2015, which seems to be the version you're targeting, but I think it will still work for VS2013), but I'm looking for somebody on campus to confirm.

**Comment by richardpawson** [comment]
I've adopted your connection string (but without the AttachDbFilename clause) and it worked OK for me. So let's hope that causes fewer failures for people.  I've also added more explanation into the documentation -  to advise that the long-pause-500-error on start-up is most likely to be a failure to connect to or create the database and to check the connection string.

**Comment by richardpawson** [comment]
FYI, in Beta6 (just released) we have significantly improved the error logging, and switched it on by default in the Template app.  If, on starting an app, the client fails to connect to the server, look in the nakedobjects_log.txt file in the project directory.
