### ISSUE TITLE
Feature request: Hidden(WhenTo.WhenNotInTableView)

### ISSUE THREAD

**Issue by smiltenburg** [NakedObjectsGroup/NakedObjectsFramework#121]
I have an object with a field which resembles something like "comments"
It is usefull to show to the user in a table view for the overview but since the text can be long this would distort the layout. I work around this by shortening the text with an extra property that is specific for the table layout. Something like:

```
 public virtual string CommentShort
        {
            get
            {
                var text = Comment;
                if (text.Length >= 40)
                {
                    text = text.Substring(0, 37) + "...";
                }
                return text;
            }
        }
```

My problem is that, to my knowledge, there is no way only show this property when shown in the tableview. When a user opens the object they will see the Comment property as well as the CommentShort property.

There is [Hidden(WhenTo.Always)] but this will hide it also from the tableview

**Comment by richardpawson** [comment]
You could probably achieve what you want using [PresentationHint()] and then customising the CSS for the object view component.  But you will need to be building the client for that.

**Comment by smiltenburg** [comment]
Hi Richard,
Thanks for your suggestion.
Although adding the annotation PresentationHint and building the client might solve my issue (given the size of what I'm trying to accomplish) it seems like something I want to avoid. Adding this extra complexity to the build of my application is quite a step to take.

In my opinion the current styling options are very minimal (choosing a color per entity).
It would be very helpfull if there were more specific css classes to style with.

My suggestion would be to include a convention that adds stuff like 
class="entityname_<MyEntityName>" , 
class="tableview",
class="propertyname_<MyPropertyName>"  
instead of just generic "property"  and "collection" css classes

This way there is a per-entity css class hierarchy to set style triggers on for each property without the need to use any custom templates

**Comment by dannief** [comment]
_**Plus 1**_ for adding css classes in the UI to allow for greater customization beyond domain type colors.

I want to suggest another class naming convention: __multiple classes instead of underscores__. In addition to adding descriptive and semantic class names. I also think that semantic class names should be added across the board to all UI elements including buttons (Save, Cancel etc), menus and menu items

Also what if __presentation hint could be added to the UI as default, using a data attribute__? This would allow even greater customization and flexibility without having to create a custom component and build the UI project. 

See example below:


```C#
[PresentationHint("collections-on-right no-tab")]
public class ExpenseReport 
{
  public virtual int Id { get; set; }
  public virtual string Description{ get; set; }
  public virtual DateTime CreatedDate { get; set; }

  [PresentationHint("rich-text extra-wide")]
  public virtual string Comment { get; set; }
  
  [PresentationHint("button")]
  public virtual Project Project { get; set; }
  public virtual ICollection<ExpenseLine> ExpenseLines { get; set; } = new List<ExpenseLine>(); 
}

public class ExpenseLine
{
  public virtual int Id { get; set; }
  public virtual int LineNumber { get; set; }
  public virtual string Description { get; set; }
  public virtual string ExpenseType { get; set; }
  public virtual decimal Cost{ get; set; }
}

public class Project
{
 public virtual string Code  { get; set; }
 public virtual string Name { get;set; }
}

```
```html
<input type="button" class="save" value="Save"/>
<input type="button" class="cancel" value="Cancel"/>
...
<div 
  class="object view ExpenseReport" 
  data-nof-presentationhint="collections-on-right no-tab"
>
  ...
  <div class="properties ExpenseReport">
     <div class="property Description">...</div>
     <div class="property CreatedDate">...</div>
     <div class="property Comment" data-nof-presentationhint="rich-text extra-wide">...</div>
     <div class="property Project" data-nof-presentationhint="button">...</div>
      ...
  </div>
  ...
  <div class="collections">
     <div class="collection ExpenseLine">
       <table>
          <thead>
              <tr>
                 <th class="LineNumber"></th>
                 <th class="Description"></th>  
                 ...
              <tr>
          <thead>
          <tbody>
             <tr>
                <td class="LineNumber"></th>
                <td class="Description"></th>
                ...
             </tr>
          </tbody>
       </table>
     </div>
      ...
  </div>
</div>
```
