### ISSUE TITLE
tableview columns not rendering when not eagerly rendered

### ISSUE THREAD

**Issue by sjorsmiltenburg** [NakedObjectsGroup/NakedObjectsFramework#123]
Hi,

I found out that the following property does not render correctly (it renders only the tostring of the object, even if 'Tableview(false, x ,y, z)' is used ) when the `[Eagerly(EagerlyAttribute.Do.Rendering)]` part is omitted. This seems to me like a bug.

```
[MemberOrder(2018)]
[Optionally]
[Eagerly(EagerlyAttribute.Do.Rendering)]
[TableView(true, nameof(Opportunity.Status), nameof(Opportunity.Organisatie), nameof(Opportunity.Relatie), nameof(Opportunity.AangemaaktOp))]
public virtual ICollection<Opportunity> Opportunities
{
  get { return _opportunities.OrderByDescending(x => x.DatumGespot).ToList(); }
  set { _opportunities = value; }
}
```

**Comment by richardpawson** [comment]
Having just a TableView attributed specifies the columns to display _when the user selects the table view icon_  -  otherwise it will display as a List (i.e. only the title of the object).  Are you saying that you are not getting these columns, even if the user selects the table icon?

**Comment by sjorsmiltenburg** [comment]
ah.. I now see that I was pushing the wrong button. This explains it. 
Sorry for the confusion.
