### ISSUE TITLE
Validate with two parameters not called when persisting an existing entity

### ISSUE THREAD

**Issue by bvdoord** [NakedObjectsGroup/NakedObjectsFramework#126]
Hi,

Like I said in my previous issue I'm still learning my way around NOF9. Today I've spent quite some time debugging an issue which I now believe to be a bug.

I have a business rule concerning two properties in one of my entities. I've added a Validate method as described in the developer manual. It's called as expected when a new entity of that type is created. But when I modify the same entity after it's been persisted, the Validate method isn't called, allowing me to bypass the business rule.

In case it's relevant the properties I'm validating are a Nullable<DateTime> (DateTime?) and another one of my domain models. I've tried validating properties of other types in case has something to do with the specific types involved, but that does not seem to matter.

I've also added a validate mehtod for a single propertym in the style of  Validate[Property]. That method is correctly called when I try to modify an existing entity. Therefore I believe the Validate method with two parameters not being called is a bug.

**Comment by richardpawson** [comment]
Please paste in the actual code for the validate method and the two properties.

**Comment by bvdoord** [comment]
Looking at the code again with a fresh mind, I see what the issue is. One of my properties is annotated with [Disabled(WhenTo.OncePersisted)]. If I remove the attribute, it works. This is not unreasonable behavior, just unexpected. While the validity of that property doesn't change, the validity of my other property still depends on it.

[Hidden] seems to similarly ignore the validation. I had hoped I could work around the issue with a second property which mimics the actual property, but alas.

Is it possible to Validate hidden and/or disabled properties as if they weren't disabled?

**Comment by richardpawson** [comment]
Your Validate method can refer to the value in the other (Disabled or Hidden) property, without it being passed in as a parameter to that method.  The point being that if the property is Disabled or Hidden, then the user can't have altered it when they entered the other field -  the Validate only needs properties passed in as params if the user might have changed them. 

`
[Disabled]
public DateTime FromDate {get; set;}`

public DateTime ToDate {get; set;} 

public string ValidateToDate(DateTime value) {
  return value > FromDate ? null : "To Date must be after From Date";
}
