### ISSUE TITLE
Friendlier message if attempting to add a transient object to a collection

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#127]
If you attempt to add a transient object to a collection on a persistent object you get the message 'Unable to create proxy. Ensure that all properties are virtual and all collections ....'  -  which is misleading.  We should detect the specific case and return a more relevant error message.

**Comment by scascarini** [comment]
<img width="362" alt="2017-12-12" src="https://user-images.githubusercontent.com/4266122/33908161-5eb4a5fe-df7f-11e7-9765-4372b5ea9201.png">

**Comment by scascarini** [comment]
To update message change ProxyExplanationTransient

https://github.com/NakedObjectsGroup/NakedObjectsFramework/commit/e4b5863126e0b1ffead9bdab5d81b8e9efc919fb#diff-cddd73bb3e5a3f8cf1a470e3401c503dR412
