### ISSUE TITLE
Action hidden-until-persisted does not show until persisted object is refreshed

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#128]
This appears to be similar to #104.  It is easy to reproduce

**Comment by scascarini** [comment]
Two parts to bug. 
1. Actions marked hidden  until-persisted don't show until object reloaded.
2. When an action creates and new object ,persists it with Container.Persist and returns it actions and properties with hidden until-persisted are not shown until reloaded

**Comment by scascarini** [comment]
Fixed and tests added
