### ISSUE TITLE
Error on TimeSpan properties

### ISSUE THREAD

**Issue by NateEichenlaub** [NakedObjectsGroup/NakedObjectsFramework#13]
I am receiving the following error on objects with properties of type TimeSpan:

> TypeError: Cannot read property 'href' of null
>     at setupReference (nakedobjects.services.viewmodelfactory.js:339)
>     at nakedobjects.services.viewmodelfactory.js:490
>     at callIfChanged (nakedobjects.services.viewmodelfactory.js:453)
>     at PropertyViewModel.propertyViewModel.refresh (nakedobjects.services.viewmodelfactory.js:488)
>     at viewModelFactory.propertyViewModel (nakedobjects.services.viewmodelfactory.js:493)
>     at nakedobjects.viewmodels.js:721
>     at lodash.js:3063
>     at lodash.js:4141
>     at baseForOwn (lodash.js:2667)
>     at lodash.js:4110

It seems as though the TimeSpan type is being treated as a reference type

**Comment by richardpawson** [comment]
Naked Objects is not set up to recognise TimeSpan as a 'value type' (the full list of recognised value types is in the Developer Manual). The easiest thing to do is:

1. Mark your TimeSpan property with [NakedObjectsIgnore]
. This will then be ignored by the Reflector and hence also never displayed to the user.
2. Create another read-only property of type string, which derives its value from the Timespan.  
3. You can also make this read-write, by parsing the input in the setter and updating the underlying TimeSpan property.  However, if you make it Read/Write you need to mark it up with [NotPersisted] for Naked Objects, and also indicate to Entity Framework that this field is not mapped to any database column.

**Comment by NateEichenlaub** [comment]
System.TimeSpan is listed as a recognized value type in the Developer Manual and worked without issue in NOF7. Is it no longer supported in version 8?

**Comment by richardpawson** [comment]
Oh, I apologize -  I was working from memory -  and didn't recall ever using TimeSpan personally.  And I hadn't realised you were referring to NOF8.  My guess now is that TimeSpan isn't provided for in the RO spec  (but I could be wrong on that one also).  It would have to be treated as a string (as there's no JavaScript equivalent), but we could possibly add a x-ro-nof extension to indicate that it is to be rendered timespan.  I infer that you have used this in an existing NOF7 app and want to now run it with NOF8 ?   I can't promise to fix this immediately as we have a lot of higher priority items on NOF8 to do. Do you use TimeSpan a lot, or would it be feasible to use the patch I suggested for the time being?

**Comment by NateEichenlaub** [comment]
Yes, I am trying to use a domain model from an existing NOF7 application with NOF8. The use of TimeSpan properties was kind of a workaround to begin with - since the NOF7 UI only allows entry of the date part of DateTime types, properties where the time part of the DateTime was needed were split into two separate properties -  a Date property of type DateTime and a Time property of type TimeSpan. This works great in NOF7, with the framework automatically handling masking and validation of the TimeSpan type in the UI. I could change the type of the time properties from TimeSpan to a string or number and still be able to construct a DateTime behind the scenes, but that would require me to also handle masking and validation, which were handled by the framework in NOF7.

**Comment by NateEichenlaub** [comment]
I just noticed a new section in the Developer Manual - How to work with date properties - that sheds some light on this issue. Adding the [DataType(DataType.DateTime)] attribute to date properties as suggested renders the DateTime type as the full date + time in NOF8 and not just the date part. Unfortunately this removes the datepicker control from the input in edit mode, but it seems like the HTML5 datetime-local input type could be used to easily correct this problem. While this provides a potential solution to my issue, the support of TimeSpan types would be preferred, as combined date-time types are notoriously problematic in JavaScript.

**Comment by richardpawson** [comment]
OK, we will commit to supporting TimeSpan again before we get to the Release Candidate for NOF8  -  but unlikely to be in the next Beta.

**Comment by richardpawson** [comment]
Fixed in Beta6 -  just released.
