### ISSUE TITLE
Unclear which fields are required

### ISSUE THREAD

**Issue by bvdoord** [NakedObjectsGroup/NakedObjectsFramework#132]
Hello,

One of my users noticed that sometimes it's hard to see which fields are required. I've looked into this a bit to see whether or not it's possible to include the standard * after the field label, but so far I've been unable to do this. Unlike with adding a new entity, the save button isn't disabled and hovering over it doesn't give a hint about which field is required. I had hoped the required attribute would be set on the input fields, but it isn't.

I know text fields do show the * as the placeholder when they're required, but in this case it's a drop down list.

Thanks!

**Comment by richardpawson** [comment]
I'm having difficulty understanding what you are asking.  Can you please include a _minimal_ example that shows the issue? Include the full code for the _minimal_ class you are trying to save and preferably a screenshot showing which fields are not showing up with the mandatory indicator.  Thanks

**Comment by richardpawson** [comment]
Note: there was an issue with missing mandatory indicators (see #115 ) -  but that specific was fixed.  So please also confirm you are using the latest release of the client code.
