### ISSUE TITLE
Issues with IViewModelEdit after having swapped panes, partially completed

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#133]
(Reported by a third-party offline) There appear to be several issues with IViewModelEdits when you swap panes -  but I suspect they are all closely related.  You can easily reproduce at least some of them quite simply on the AdventureWorks demo, as follows:

1. From a Contact create an Email (which is an IViewModelEdit) e.g. Contacts > Random Contact > Actions > Create Email
2. Swapping panes at this point (i.e. without any fields entered) does not result in any issue, and nor (if you try it) does the empty email appear in Recently Viewed.
3. If you now start entering data into any field on the Email and then swap panes, or perform any other action that causes the Email to be re-rendered, you will find that the Email has now appeared in the Recently Viewed.  This makes sense to me, though I noted (I think!) that this was also causing the view model to be re-fetched from the server -  not entirely unexpected to me, but is this correct?
4. If you now click on the link to the email from Recently Viewed, however, the email, despite being an IViewModelEdit (not a IViewModelSwitchable even) appears in view (not edit) mode and does not show the contents of the field that the user has entered.
5. After this, things go downhill rapidly.  Further edits and pane swaps can for example result in blank panes.
6. As originally reported to me (on another application) the user was unable to invoke the (zero param) action they had on their IViewModelEdit (this was only after having swapped panes and looked at the recently-viewed  -  it worked without those interventions) -  but that might be because their action depends on field values or some such (because on the AdventureWorks example you can still invoke the Send action).

So, issues to sort out:

- Should the view model edit be appearing in the Recently Viewed after a pane-swap?  If it should, why does it not appear to be held in edit mode?

**Comment by scascarini** [comment]
Looking through the code it seems clear that the original intention was that 'forms' i.e. editable view models would not appear in the recently viewed list. So it looks like the fact that they get added in certain scenarios is a bug. 

A fix would be make sure the form never gets added, and test scenarios with pane swaps etc. To check there are no other underlying problems.

If having forms in the recently viewed list is something we want to do we should probably create a feature ticket for it and we could do it in 9.1.

**Comment by richardpawson** [comment]
Thanks  -  I see no need for the editable form to be in the recently viewed list -  if that cures the problem.

 

BTW, another quite significant bug surfaced at school today, which is a bit surprising.  If you have a DateTime property that is the last (i.e. lowest on screen) property then (on a transient object at least) the value you enter isn’t taken on by the form when you hit Save -  and you get back a ‘Please complete all required fields’ message!  Problem disappears if you move the DateTime property up with MemberOrder.

 

I have a vague memory of a similar problem on a much earlier version of NOF. 

 

I haven’t tested Dialogs  -  we should do that also in case it applies there too.

 

I want to get my pupils to file the Issue on GitHub, but if they don’t do it quickly, I’ll add it myself.  But so you know …

 

Richard

**Comment by richardpawson** [comment]
Fixed in 9.0.4
