### ISSUE TITLE
Absolute hyperlinks in manual

### ISSUE THREAD

**Issue by dannief** [NakedObjectsGroup/NakedObjectsFramework#136]
The links in the manual all point to an absolute location at : `C:\NakedObjectFramework\Documentation`

The popup below displays whenever a link is clicked.

![image](https://user-images.githubusercontent.com/6110488/35951948-a7c06e60-0c4b-11e8-8279-e35e23b0d3d0.png)

I was able to fix the issue in my copy by selecting `Alt + F9` on my keyboard. This displayed the hyperlink data and allowed me to find and replace the absolute URLs and update the table of contents as well.

**Comment by richardpawson** [comment]
Thanks for reporting this.  I'm amazed it hasn't been spotted before (and that Word created them absolute by default!).  I have hopefully fixed it now.  I did notice in the process that one or two links were to the wrong section  -  if you come across any please report.
