### ISSUE TITLE
Upgrading from 9.0.2 to 9.0.3

### ISSUE THREAD

**Issue by bvdoord** [NakedObjectsGroup/NakedObjectsFramework#141]
Hello,

Me and a colleague have been scratching our heads at a mysterious issue. We were trying to upgrade from 9.0.2 to 9.0.3. At first glance it looked like everything went over smoothly, but as soon as you log off and log on again, you get the following error:

Error message received from server
Message: Unknown client HTTP error
Code: Unauthorized(401)
Description: An HTTP error code has been received from the server You can look up the meaning of this code in the Restful Objects specification..
Stack Trace :
No stack trace available

This seems to do with the access_token or id_token as those are cleared from the localStorage upon logging out.

I've been able to reproduce the issue by modifying the template example as described in the Authentication setting and pointing the template project to our Auth0 service. We haven't changed any of the settings in Auth0. If we must do so, I don't think they've been mentioned in the manual. Although I might be simply overlooking it.

We've upgraded from 9.0.1 to 9.0.2 without any problems. The upgrade to 9.0.4 you've released just yet doesn't help, either.

**Comment by richardpawson** [comment]
I can't imagine why that would be  -  given the changes that were made between 9.0.2 and 9.0.3.  One possible explanation is that in doing the upgrade you overwrote some file(s) that you did not intend to? Go back to working state (and check that the log off/on problem has properly gone), commit, do the upgrade again and check to see the changes made. 

Also, make sure that it's not cause by browser caching  i.e. clear all cached files in the browser.

**Comment by bvdoord** [comment]
We've tried that several times - which is why this issue is such a head scratcher. None of the changes in my repo look out of the extraordinary, mostly the .package files, the .csproj include rules, .js/.css/.html files in the client project.

To make sure it's not about accidentally overwriting files I used the template project. I just cloned the template from the repo and changed the appropriate settings - which results in the error.

When I use the developer tools to inspect the contents of the localStorage it seems the access_token and the id_token have doubles in size after logging off and on again. If I then copy the value of the token from before the upgrade onto the tokens, it works again.

**Comment by richardpawson** [comment]
OK, I am looking into this.

**Comment by richardpawson** [comment]
We have found the source of the problem  -  our mistake.  An upgrade to Auth0 code that was planned  for 9.1 was accidentally included in 9.0.4.  We will be issuing a 9.0.5 which reverts the change, but keeps other recent fixes, soon.

**Comment by richardpawson** [comment]
Fixed in 9.0.5, now released.
