### ISSUE TITLE
Validate method on single property not being called when saving a transient object

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#143]
I have a validate method for a single property.  The method is called when editing and saving an already persisted object, but it is not being called when saving a transient object.

Curiously, if I have a validate method for multiple properties (i.e. just Validate([prop list])) then that _is_ called on saving a transient.

**Comment by scascarini** [comment]
I have tested on the template project.

Added to class 'Student' 

`      public virtual string ValidateFullName(string name) {
            return name == "fail" ? "fail" : "";
        }`

Created and saved a transient Student. Validate code was hit on save (added breakpoint). If name set to 'fail' transient was not saved with error, otherwise transient saved OK. 

So looks like I'll need a bit more info to reproduce.

**Comment by richardpawson** [comment]
After a little more investigation, the problem seems to be associated with the use of authorization.  If I switch off authorization altogether (in UnityConfig) the problem disappears.

**Comment by richardpawson** [comment]
After further investigation, we have concluded that this is not a bug, though there is possibly a need for a little more documentation.  The issue is only likely to arise in very specific circumstances, and there is an easy fix.

When a transient object is saved, the system checks to see if a given field is editable.  Only if it is editable is the validate method called on it.

What was happening in this case was that the object's authorizer was returing 'false' for the IsEditable method, because the logged-on username did not correspond to the user name on the object, and nor could it, because the object was transient. Once the object was saved, the authorization was accurate and so the validate method was also being called.

In this specific circumstance, the fix is to ensure that the IsEditable method on the Authorizer also checks whether the object is Persisted or not.
