### ISSUE TITLE
Enum dropdown is displaying the enum values instead of the names

### ISSUE THREAD

**Issue by acrigney** [NakedObjectsGroup/NakedObjectsFramework#149]
When I display my list of options for an enum they display as just the numbers not the names.
I thought this type of code should do it?
public List<CourtType> ChoicesWorkCourtType(string officeName)
        {
            return CourtRepository.FindCourtsByOfficeName(officeName).Select(x => x.CourtType).ToList();            
        }

**Comment by richardpawson** [comment]
All Lists used by Naked Objects must be generic e.g List<CourtType>.  This is clearly stated in the manual.
