### ISSUE TITLE
Startup Performance

### ISSUE THREAD

**Issue by brentvee** [NakedObjectsGroup/NakedObjectsFramework#15]
Hey Richard,
I'm having a little trouble trying to get my website warmed up.
I have a layout page that uses a CustomController which has a container injected etc, that i initially browse to, to perform a warm-up of the site.
There are no menu items on this layout page, but it does request the same scripts and styles as the root layout page.

When i eventually open the root layout page that contains all the main menus, its takes about 5-10 seconds for the page to load. Thereafter, switching between menus is pretty snappy.
What is NOF requesting that takes up the extra time?
Is there something I could be doing wrong?

Thanks

**Comment by richardpawson** [comment]
Is this NOF7 or NOF8, please? Either way, though, I can't really help if you are doing custom stuff.  I can only suggest you do some profiling to find out where the time is being spent.

**Comment by brentvee** [comment]
This would be NOF 7.
It's not really custom stuff per se. 
Is there anything that NOF needs to cache in terms of Menu Services that could be taking a little longer on the first run?

**Comment by richardpawson** [comment]
I'm not sure what you mean by the first run.  Do you mean when first starting up the app, or do you mean that you have the app server already running (which you can prove with the generic UI), but you are getting a delay the first time you access your custom controller method?

**Comment by brentvee** [comment]
I have two browser tabs open. One for my dummy page, and one already containing my NOF menus.
The app server gets started up by me browsing to my dummy page that uses the NOF CustomController This correctly injects the Container etc.
Then I switch tabs to the main page for NOF and select any Main Menu, it takes a little while for it to eventually return and render my menu actions. 
Any subsequent menu selection is quick though, so it just seems to be the first one.
My apologies if this is badly explained

**Comment by richardpawson** [comment]
Menu information is cached on the session, because the menu contents may depend upon the user's authorization, I can't recall the exact start up sequence on NOF7, but it seems quite likely to me that the menu information is not constructed/cached until it is first requested by the client i.e. sometime after log-on.  

One way to test this and/or to overcome the issue, would be to ensure that the main menus are loaded by your dummy page, but just kept hidden from the user. This should then allow instant switching to the other tab (assuming they are on the same session).

**Comment by brentvee** [comment]
Ok, I'll give that a whirl (of course it presents its own problems as we use Authorizers to determine visibility of the menus).

Thanks Richard

**Comment by brentvee** [comment]
The basis of my question is due to using slot switching in Azure and having the site warmed up before swapping slots.
