### ISSUE TITLE
Update Newtonsoft.Json Dependency

### ISSUE THREAD

**Issue by VantageKR** [NakedObjectsGroup/NakedObjectsFramework#158]
Please update Newtonsoft.Json dependancy to more recent version of Newtonsoft.Json.

**Comment by VantageKR** [comment]
The dependent is NakedObjects.Rest, which depends on very old version of Newtonsoft.Json. The NakedObjects.Rest 8.1.2 beta however, depends on a more recent Newtonsoft.Json, so upgrading NakedObjects.Rest to the latest pre release version lifts the Newtonsoft.Json dependency higher.

**Comment by richardpawson** [comment]
Dependency is bumped up in NakedObjects 10.0.0-RC1 as shown here:

<dependency id="Newtonsoft.Json" version="[12.0.1, 13)" />

**Comment by richardpawson** [comment]
`<dependency id="Newtonsoft.Json" version="[12.0.1, 13)" />`
