### ISSUE TITLE
Question: Regarding Virtual Properties

### ISSUE THREAD

**Issue by johnbouma** [NakedObjectsGroup/NakedObjectsFramework#162]
While the question is quick, I have a feeling the answer might not be.  Why do all persisted properties have to be virtual in the system?  Is it used as some sort of marker for properties that EF needs to handle?

Cheers,  

John

**Comment by richardpawson** [comment]
Yes, this is a requirement imposed by EF  -  or to be more accurate by the way in which Naked Objects uses EF.  The NOF can hook into events that EF generates this way. It helps to avoid the need for any calls to the NOF when editing/updating objects via the UI.

For further explanation see, for example, https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/dd468057(v=vs.100)

**Comment by johnbouma** [comment]
I'm well aware of how/why EF6 requires virtual - was just wondering if that was essentially inherited by NOF.  For context, my group at work avoids Lazy Loading like the plague - as we have found it adds more trouble and complexity than it adds - and as interesting as NOF is to me, the lack of dotnet-core and ef-core support makes it a non-starter, but also, the fact that all those classes need to be implemented in such a way as to support lazy loading would be a hard sell. 

Thanks for the quick response.
