### ISSUE TITLE
NOF Server API and OpenAPI / Swagger

### ISSUE THREAD

**Issue by VantageKR** [NakedObjectsGroup/NakedObjectsFramework#163]
What would be the simplest way to generate API
documentation from a NOF 9 server? I've noticed that if I hit the server
URI with Firefox, I get a JSON file that looks like some kind of
specification for the API - which makes sense since that is probably
what the client Angular SPA use to generate itself.

Apart from repeatedly hitting the server, saving the JSON, and using it
to construct documentation, what else can I do?

I tried to get documentation through SwaggerUI, but it returns this message:

> Unable to render this definition
> The provided definition does not specify a valid version field.
> Please indicate a valid Swagger or OpenAPI version field. Supported
> version fields are swagger: "2.0" and those that match openapi: 3.0.n
> (for example, openapi: 3.0.0).

I got this by copying the SwaggerUI code straight on to the web server
where the NOF server is hosted from, to avoid any CORS issues.

Another thing I'm considering is to use Fiddler to record the HTTP
traffic between the browser and the NOF server?

Do you think I should get the code for the NOF Client Angular SPA and
try to reverse engineer how it interprets the NOF server REST API?

Any help or advice would be much appreciated.

**Comment by richardpawson** [comment]
The RESTful API conforms to the Restful Objects Specification -  which is one of the most comprehensively documented  Restful APIs in existence.  Visit the Restful Objects website, which has links to Word and .pdf versions of the spec -  which runs to nearly 200 pages in total:

http://www.restfulobjects.org/index.html 

This spec, which I had a hand in developing, but was the brainchild of Dan Haywood, is what we actually used to design and test the API between NOF server and client. 

Note that in later versions we made some small optional additions to the API (which the spec, permits).  These are not properly documented yet, at least not in electronic form, but they are fairly easy to discover.

Please also note that in version 10 of the NOF, the client has been split up into multiple NPM packages.  The idea is that the lower levels of the stack interact with the RO API and produce enriched versions of the representations, and these are in turn consumed by the higher-level packages which generate a specific UI.

**Comment by VantageKR** [comment]
Thanks @Richard, so is it fair to say that a developer armed with a basic understanding of the RestfulObjects specification, together with an understanding of the domain model exposed through the NOF server, would fairly easily be able to develop against the REST API then?

**Comment by richardpawson** [comment]
Yes -  if they understand REST at all then the Restful Objects Specification is a comprehensive documentation of the whole API generated by the NOF server.  The only exceptions are a _very small_ number of custom extensions (i.e. not covered by the general RO spec).  Conveniently, these are all defined in a single [source code file](https://github.com/NakedObjectsGroup/NakedObjectsFramework/blob/master/Spa2/nakedobjectsspa/restful-objects/src/ro-interfaces-custom.ts)

**Comment by VantageKR** [comment]
Having explored the RestfullObjects REST API server output, and having read the spec for RestfullObjects a bit, I am very impressed!
This is an extremely powerful and complete and logical way of interacting with a domain model.
