### ISSUE TITLE
Authentication via OpenID Connect with a IdentityServer4-based authenticator service

### ISSUE THREAD

**Issue by VantageKR** [NakedObjectsGroup/NakedObjectsFramework#164]
I'd like to replace the AuthZero authentication provider service with an already built and working custom, IdentityServer4-based OpenIDConnect authentication service.
has anyone been able to do this before? Any tips / tricks / things to lookout for?

**Comment by richardpawson** [comment]
We have no experience to offer on this one, sorry.
