### ISSUE TITLE
More efficient EF code for delete and update through EFPlus

### ISSUE THREAD

**Issue by VantageKR** [NakedObjectsGroup/NakedObjectsFramework#165]
For actions such as updating or deleting a large number of objects, there exists EntityFrameworkPlus:

**Comment by VantageKR** [comment]
https://entityframework-plus.net/

This package makes it possible to generate UPDATE and DELETE SQL statements for a single trip to the database where possible. How would one use this in NOF?
I've tried, but it seems that EFPlus encounters unset properties in the model object passed to it. Here is an example of what I've tried:

```c#
int[] ids = new int[]{1,2,3,};
this.Container.Instances<Person>()
.Where(p => ids.Contains(p.Id))
.Update(x => new Person() { Name = "New Name" });
```

This should result in a single UPDATE SQL statement with an IN clause on the ids.
I suspect the "new Person() { .. }" creates a Person instance that is obviously not injected and properly instantiated by NOF, and that EFPlus then hits null valued members on reflection.
  

Any suggestions? Would be great to get this type of SQL generated, without the cumbersome approach of writing a stored procedure, or SQL code directly through the db context.

**Comment by VantageKR** [comment]
Didn't meant to close the issue, so here it is opened again.

**Comment by richardpawson** [comment]
As you say, this method is designed for doing bulk update in  the database without bringing the objects into memory.  So the objects are never coming into the realm of the NOF, hence you are not going to get any service injection. That makes sense to me. There's no way I can think of to somehow get the best of both worlds because that would not make sense.

**Comment by VantageKR** [comment]
Well, it makes sense in that, for getting EF to construct an UPDATE SQL statement to act on multiple rows, where the columns being updated is non reference types, this library should in theory be able to use reflection to construct the query - as in the example I posted and same can be found on their site.
It seems that EFPlus is throwing the null ref exception, so my theory is that after the parameterless constructor is called on the model object, during the process of reflection it hits a null valued member.
If the above could be overcome, then the next issue would be to somehow let the container know that the objects updated in this way should be fetched afresh from the database, so not that they are dirty and need to be persisted, but that they need to be refreshed.
The fact that EFPlus is throwing the null ref exception doesn't seem to me to be caused by NOF. I would have to dig deeper to solve this, but there are higher priorities in the system, so this will have to wait.
