### ISSUE TITLE
NOF on .Net Core?

### ISSUE THREAD

**Issue by VantageKR** [NakedObjectsGroup/NakedObjectsFramework#167]
As per:
https://devblogs.microsoft.com/dotnet/net-core-is-the-future-of-net/

"
With the .NET Core 3.0 release in September 2019 we think that all *new* .NET applications should be based on .NET Core. The primary application types from .NET Framework are supported, and where we did not port something over there is a recommended modern replacement. All future investment in .NET will be in .NET Core. This includes: Runtime, JIT, AOT, GC, BCL (Base Class Library), C#, VB.NET, F#, ASP.NET, Entity Framework, ML.NET, WinForms, WPF and Xamarin. 
"

Notice the : "... All future investment in .NET will be in .NET Core". When could we expect a .Net Core port of NOF?

Any significant blockers / challenges?

**Comment by richardpawson** [comment]
We had a go at porting to .NET Core over a year ago, but it was too difficult  -  Microsoft had made too many arbitrary and unnecessary changes. Also, Entity Framework was still a big issue then.  My understanding of .NET Core 3 is that Microsoft has addressed many of these issues, so we are hopeful about moving NOF to .NET Core 3, possibly in NOF 11.  But we are not giving any indication of timescale for this as yet.

**Comment by richardpawson** [comment]
The latest release of the NOF Server, currently at 11.0.0-rc01 -  runs on .NET core
