### ISSUE TITLE
Sortability by TableView column header

### ISSUE THREAD

**Issue by VantageKR** [NakedObjectsGroup/NakedObjectsFramework#169]
Could the Angular NOF 10 auto-generated UI be extended to support this?
Often times the ordering of rows in a TableView on a collection is not ideal.
We are getting past this by defining ContributedAction methods, but this is not dynamic and burdensome for views with many columns.
Would be really great if a click on a column header could sort by that column header, even if only for the currently displayed page in the event of paged output.
Thanks for such an awesome auto-generated UI we have with NOF 10 already!

**Comment by richardpawson** [comment]
> _Could_ the Angular NOF 10 auto-generated UI be extended to support this?

Yes.  Do we have any plans to do it?  No.  

(FYI, to forestall further requests ... we are not yet planning any further functional extensions of the client for a substantial period, as our focus has now returned to the server side.)
