### ISSUE TITLE
MemberOrder attribute not correctly ordering member properties

### ISSUE THREAD

**Issue by VantageKR** [NakedObjectsGroup/NakedObjectsFramework#170]
Reading in the latest NOF 10 manual that the MemberOrder attribute should be ordering based on the standard string comparator for the argument (string or double), I tried strings and doubles, but the ordering is not performed.
Are there perhaps any other factors that could "break" this ordering mechanism, or any other things to keep in mind about this?

**Comment by VantageKR** [comment]
I can confirm that the REST API correctly sends through the "memberOrder" attribute in the JSON payload, and it even comes in in the correct order, yet the client does not respect this ordering.
The Client is also NOF 10, taken from the Template solution.

**Comment by richardpawson** [comment]
I know that member order is definitely working on the NOF10 client, for integer values (which, I confess, I have only ever used).  It is _possible_  that the NOF 10 client, which, of course, uses the JavaScript type system, not the .NET type system, assumes they are integers and ignores anything that doesn't convert.  I can't say for sure off the cuff, but you might confirm that member order with integer numbers is working.  If necessary I will update the documentation to state this.

**Comment by richardpawson** [comment]
Kerneels

 

You know that it is working, because I generally respond to your requests where I have something to say.  But this is a voluntary exercise and we do not offer a minimum service level agreement.   Chasing me via email is neither necessary, nor effective.

 

Richard

**Comment by VantageKR** [comment]
Richard,
Yes, I knew that it was working before, but no, I was not sure that it was working now since the GitHub issue page read out a lot of additional text, as well as a message that the action was unsuccessful. 
I apologise that my email might have come across as "chasing you", but in all honesty, you are free to ignore it if you were busy or simply unwilling to respond, and, I was really trying to determine if the issues submitted properly and not to chase you.

Of course we  know all of NOF support is a voluntary effort, and we are grateful for the support if any ever, and of course we  do not assume any kind of service level agreement.

**Comment by VantageKR** [comment]
Note that I'm using integer arguments to MemberOrder, and that the total compliment of properties for the concrete object is composed from some abstract super classes, and some concrete super classes, but all properties are numbered such as to have the correct order, but they do not.

Have also tried clearing the complete browser history. I'm running the client on latest Firefox, and running everything through IIS Express in Visual Studio.
As mentioned, the REST JSON correctly sends through the member-order integers, and it even physically places them in the right order in the JSON.
Anyone else experienced issues with the ordering perhaps?

We understand that development resources will be focusing  on the server for the immediate future, but allow us to use this forum to troubleshoot and discuss in the community - thanks.
