### ISSUE TITLE
RTL user interface?

### ISSUE THREAD

**Issue by ury** [NakedObjectsGroup/NakedObjectsFramework#171]
Hi Richard,
Version 10 looks great!   I think I have a project which is a good candidate for it.  The thing is, the user interface must be in Hebrew, that is right-to-left, right-aligned etc.
Does the Gemini UI support RTL?  If so, how?
Thanks,
  Ury

**Comment by richardpawson** [comment]
Good to hear, Ury. 

Gemini has no specific provision for that form internationalisation.  However, in NOF 10 we have separated the client UI into distinct layers, allowing you to customise the detailed operation of Gemini, while using the underlying layers (that do the interaction with the server and unpack the RO representations.  The top layer (Gemini) is pretty standard Angular coding. If you wanted to create and re-distribute a Hebrew version of the top layer as a Node.js package, then that would be welcomed.

**Comment by ury** [comment]
Thanks Richard,
It would be my first experience with Angular, but I'll take a look at the code.

**Comment by ury** [comment]
Hi again,
I'm trying to set up the angular development environment.
When I run "ng build", I'm getting the following errors:

**ERROR in src/app/app-routing.module.ts(3,33): error TS2307: Cannot find module '@nakedobjects/cicero'.
src/app/app-routing.module.ts(15,8): error TS2307: Cannot find module '@nakedobjects/gemini'.
src/app/app-routing.module.ts(16,39): error TS2307: Cannot find module '@nakedobjects/services'.
src/app/app.component.ts(2,63): error TS2307: Cannot find module '@nakedobjects/services'.
src/app/app.module.ts(5,43): error TS2307: Cannot find module '@nakedobjects/cicero'.
src/app/app.module.ts(6,43): error TS2307: Cannot find module '@nakedobjects/gemini'.
src/app/app.module.ts(7,45): error TS2307: Cannot find module '@nakedobjects/services'.
src/app/app.module.ts(8,46): error TS2307: Cannot find module '@nakedobjects/view-models'.**

Any idea?
Thanks,
  Ury

**Comment by scascarini** [comment]
Try

npm install -g yarn
npm install -g @angular/cli@7.3.1
cd <where you've cloned to>\Spa2\nakedobjectsspa
npm i
npm run prepackage

yarn build:libs
yarn build:app

ng build  --prod

**Comment by ury** [comment]
Thanks Stefano.
I performed all of the above.

1. "ng build --prod" was done instantly without any output.  Is this ok?
2. I don't see the built output anywhere.  Where should it reside?
3. In the future, if I'm modifying only the Gemini sources, which of the above commands should I repeat?

**Comment by scascarini** [comment]
I get something like

Date: 2019-07-17T10:48:56.152Z
897
<https://ci.appveyor.com/project/scascarini/nakedobjectsframework-bvpgo#L897>Hash:
7987373e057da41693eb
898
<https://ci.appveyor.com/project/scascarini/nakedobjectsframework-bvpgo#L898>Time:
103157ms
899
<https://ci.appveyor.com/project/scascarini/nakedobjectsframework-bvpgo#L899>chunk
{0} runtime.26209474bfa8dc87a77c.js (runtime) 1.41 kB [entry] [rendered]
900
<https://ci.appveyor.com/project/scascarini/nakedobjectsframework-bvpgo#L900>chunk
{1} main.2b8a7ef3e4c9167fb300.js (main) 1.93 MB [initial] [rendered]
901
<https://ci.appveyor.com/project/scascarini/nakedobjectsframework-bvpgo#L901>chunk
{2} polyfills.5d3fb9493999a51d6359.js (polyfills) 41 kB [initial] [rendered]
902
<https://ci.appveyor.com/project/scascarini/nakedobjectsframework-bvpgo#L902>chunk
{3} styles.2f01a7a557ae9d7bf896.css (styles) 11.9 kB [initial] [rendered]

Output under dist\nakedobjectsspa I think.

if you just changed gemini you should be able to do

yarn build:gemini
and then
yarn build:app
ng build --prod.

**Comment by ury** [comment]
Hi Stefano,
My NakedObjectsFramework-master\spa2\nakedobjectsspa\dist folder contains the following:
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        7/17/2019   4:20 PM                app
d-----        7/17/2019   4:19 PM                nakedobjects-cicero
d-----        7/17/2019   4:18 PM                nakedobjects-gemini
d-----        7/17/2019   4:16 PM                nakedobjects-restful-objects
d-----        7/17/2019   4:16 PM                nakedobjects-services
d-----        7/17/2019   4:17 PM                nakedobjects-view-models
d-----        7/17/2019  12:22 PM                out-tsc

The app subfolder contains the following files:
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        7/17/2019   4:20 PM                assets
-a----        7/17/2019   4:20 PM           5430 favicon.ico
-a----        7/17/2019   4:20 PM          60392 iconFont.eot
-a----        7/17/2019   4:20 PM         314050 iconFont.svg
-a----        7/17/2019   4:20 PM          60224 iconFont.ttf
-a----        7/17/2019   4:20 PM          83060 iconFont.woff
-a----        7/17/2019   4:20 PM            745 index.html
-a----        7/17/2019   4:20 PM          79518 main.js
-a----        7/17/2019   4:20 PM          83479 main.js.map
-a----        7/17/2019   4:20 PM         242170 polyfills.js
-a----        7/17/2019   4:20 PM         240978 polyfills.js.map
-a----        7/17/2019   4:20 PM           6224 runtime.js
-a----        7/17/2019   4:20 PM           6214 runtime.js.map
-a----        7/17/2019   4:20 PM          32095 styles.js
-a----        7/17/2019   4:20 PM          36046 styles.js.map
-a----        7/17/2019   4:20 PM        7755467 vendor.js
-a----        7/17/2019   4:20 PM        8270870 vendor.js.map

Is this how it is supposed to be?
What do I need to do from here in order to have an updated Template.Client project?

**Comment by scascarini** [comment]
Our appveyor build console is here.

I think you should be able to follow all the steps from it.

https://ci.appveyor.com/project/scascarini/nakedobjectsframework-bvpgo
