### ISSUE TITLE
[MultiLine] attribute, applied to actions with choices methods not functioning as expected

### ISSUE THREAD

**Issue by VantageKR** [NakedObjectsGroup/NakedObjectsFramework#174]
Hi. I'm eager to make use of the [MultiLine] attribute as applied to actions, to achieve a grid-like interface for repeated action invocation, but not able to get it working.
The action I'm applying it to works perfectly without it. The action has drop down lists, in the choices style, where one drop down affects the choices available in the following one.
The action is rendered properly, but the OK buttons do not actually submit each line, since the counter at the bottom, next to the CANCEL button stays at "0 rows submitted". After adding a row or two, the OK buttons remain next to the rows added (I believe they should change to a delete button?), and nothing changes in the database.
How can I debug this other than looking at Fiddler traces? Has anyone used this attribute on an action with the choices-style of parameter selection?

**Comment by richardpawson** [comment]
Well you can certainly establishing, via Fiddler, whether hitting OK on a line is making a submission to the server or not, and if it is, what is coming back. 

If you are concerned that the dependent Choices is the issue (it might be -  I don't think that's a scenario we've explicitly tested on multi-line actions)  then temporarily patch that out in favour of simple choices and try again.
