### ISSUE TITLE
Eager loading of collections

### ISSUE THREAD

**Issue by VantageKR** [NakedObjectsGroup/NakedObjectsFramework#176]
Through the manual and from prior knowledge, I'm aware that one can use the `.Include` extension  method on Linq queries to eagerly load related entities, but how can this be achieved if the entity is navigated to in the UI?
Even when marking up a collection with `[Eagerly(EagerlyAttribute.Do.Rendering)]`, along with a `[TableView( ... )]` attribute, the only effect is that the entity is rendered with the collection expanded and loaded in full, however looking at the SQL Server query store this is a second query on the entity.
Is there perhaps a way to bundle the collection loading query with the first query retrieving the other non navigation properties of the entity?
Note that the collection eagerly loaded is bounded and typically ~50 entities in total, yet the loading time for the entity is too slow.

**Comment by richardpawson** [comment]
If your query that retrieves object A from the database also explicitly .Includes, or otherwise loads, the associated objects then Entity Framework should cache the latter automatically - so that even if the client requests the (eager) loading of associated objects via separate Http requests, it should not, I believe, hit the database again in rendering that view.

**Comment by VantageKR** [comment]
Yes, that makes sense that it should be possible for EntityFramework to do that, and I really hope it does.
However, the initial load of the object A is through clicking on a link in the UI, so it is through an HTTP REST GET request for the object. What I'm after is for that first HTTP GET to load the associated collection on object A in that same call, as if object A was being returned from a Linq query with `.Include( ... )` applied to it.
The marking up of the collection with `[Eagerly(EagerlyAttribute.Do.Rendering)]` almost need extending such that it would be possible to say: `[Eagerly(EagerlyAttribute.Do.Rendering, EagerlyAttribute.Do.Loading)]` which will cause the eager loading of just that collection when browsing to it, but not in a separate query but as part of the main query for the instance load of object A.
It would not do to configure the service to recursively, eagerly load everything; there need to be some control as to which dependant navigation properties gets eagerly loaded.
Alternatively, is there perhaps a life cycle method that could achieve this; add the `.Include( ... )` to the query to load the entity?
