### ISSUE TITLE
Number of entries in the "recent objects" feature

### ISSUE THREAD

**Issue by VantageKR** [NakedObjectsGroup/NakedObjectsFramework#177]
Is there perhaps a configuration setting for the number of items in the "recent objects" feature in the client? I'd like to increase that a little bit. Very useful feature of the client.

**Comment by scascarini** [comment]
recentCacheDepth in config.json.  Be wary of increasing too much and monitor memory usage.

**Comment by VantageKR** [comment]
Thanks Stefano; saw that setting in the user manual, but thought it was only to do with actual caching. Will try it out and monitor memory usage.

On 25/07/2019 08:41, Stefano Cascarini wrote:

recentCacheDepth in config.json. Be wary of increasing too much and monitor memory usage.
