### ISSUE TITLE
Auditing Framework and Exceptions / Errors

### ISSUE THREAD

**Issue by VantageKR** [NakedObjectsGroup/NakedObjectsFramework#178]
Hi. What is the current expected behavior of the auditing system in NOF, when exceptions are encountered on anything that should be audited? For example, if an exception is thrown during the execution of an action that is all setup to be audited, where does the exception go, is anything audited or does the exception throwing preempt the auditing? How about raising an error manually during the invocation of an action that is audited; how should this be done? Are there life cycle methods involved in the auditing? Thanks.

**Comment by richardpawson** [comment]
I couldn't tell you, I'm afraid.  I suggest doing a spike and investigating the behaviour.

**Comment by VantageKR** [comment]
You are afraid @richardpawson? Imagine how scared am I! :) Thanks for the response, and I'll feedback on my findings if we choose to implement auditing through what NOF provides, which I hope for. Am I correct in that, should exceptions not be handled at all, one can always implement try / catch logic and explicitly call the audit service in such a way that the exception could get audited?
