### ISSUE TITLE
Checkpointing behaviour / partial commit of transactions in long running actions

### ISSUE THREAD

**Issue by VantageKR** [NakedObjectsGroup/NakedObjectsFramework#179]
For longer running actions dealing with multiple entities, is it possible to achieve checkpointing behaviour / partial commit for members of the collection being processed that did not fail in any way?

**Comment by VantageKR** [comment]
From the manual I understand that it is possible to cause an abort, but is it possible to commit what succeeded?
If not, what other strategies exist for dealing with long running actions that could be easily implemented in the framework?
The async ability of the framework seems only to be available when run as a stand alone executable, and not in an HTTP context, understandably.
Is this the point where the long running action should be implemented in  a stand alone executable; in a kind of processor; where the main REST API would queue long running actions, and the stand alone processor work away at them, potentially multi threaded and asynchronously dealing with external systems?

**Comment by richardpawson** [comment]
Naked Objects treats every user-initiated action as an all-or-nothing transaction. This is managed by Microsoft transaction constructs.  We have no experience of attempting a 'partial commit' as you describe, and would be very wary of it. It suggests to me that something is wrong with your model if you are _expecting_ to encounter errors in the execution of a single user action, and want to manage around that. You should be doing the checking before starting the action.
