### ISSUE TITLE
Template Example Saving Student not working

### ISSUE THREAD

**Issue by erdoll** [NakedObjectsGroup/NakedObjectsFramework#183]
Hello,
I am attempting to get the Template example solution working.

It mostly works, except for Saving a new student.

Here is what I have done and seen.
1. Switch database to local sqlexpress.  The database is created, seeming correctly.

2.  I got an error that the roslyn complier could not be found - with some googling on the error message I ran 
Update-Package Microsoft.CodeDom.Providers.DotNetCompilerPlatform -r
which fixed the problem.

3.  Things that work:
a. Home page
b. List students
c. Edit students
d. Find student
For these operations there are no error messages in the browser console (Chrome 79), and all the http operations return 200 codes.

4. But saving a student is failing.
a. The post being made when you select to Create a New Student is working
OPTION and POST requests both return 200 to this url
http://localhost:5000/services/Template.Model.ExampleService/actions/CreateNewStudent/invoke
and it will hit a break point in the CreateNewStudent() member of ExampleService

b. However, clicking save brings up this error on the web page.
Client Error
Message: Failed to connect to server: http://localhost:5000/objects/Template.Model.Student
Code: ConnectionProblem
Description: The requested view of unsaved object details has expired.
Stack Trace :
No stack trace available

And 
OPTIONS HTTP request to http://localhost:5000/objects/Template.Model.Student  returns 404

and in the console I see

Access to XMLHttpRequest at 'http://localhost:5000/objects/Template.Model.Student' from origin 'http://localhost:5001' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

and  no log file is being created on the server with a log message.

So, all the prior http calls are successful vis-a-vis CORS, but not the failing one. (Unless the error message is misleading.)

I have also tried to update Nuget packages (27 are shown as Updates available), but I quickly get into DLL hell. Particularly log4net, unity and system.collections.immutable have constraint issues in updating.  Entity framework will update find by itself and the code works.  Updating all the Owin and IdentityModel packages causes runtime errors on assembly resolution.  So, I abandoned my attempt to fix this issue via Nuget updates.

Do you have some direction you can provide to get the Saving of students operation working?  (Short of pulling the source and debugging?)

Thanks, Roger

**Comment by richardpawson** [comment]
Just wanted to let you know that we are looking into this, and will report back soon.

**Comment by richardpawson** [comment]
There seems to be some sort of 'bit decay' problem here i.e. something that definitely was working has stopped working with environment updates. We're not entirely sure when or why, but I'll tell you what we've found.

The 404 is happening because it is not matching the URL, and this seems to be cause by the existence of a '.' in the domain type part of the URL  -  which has never been a problem in the past.

We found a fix for this, although we can't profess to fully understand the issue, or this fix. In the web.config, add the new line shown below:

```
<system.webServer>
  <modules runAllManagedModulesForAllRequests="true"/>
    
  (...existing handler stuff here ..) 

  </system.webServer> 
```

**Comment by erdoll** [comment]
Thanks Richard.

That change fixed it.  

BTW, years ago, before Naked Objects went open source, I actually purchased a license to it.  We had a use case for building low cost simple administrative interfaces for CRUD operations on applications with small databases.  I was intrigued by the Naked Object concept applied to that use case.  We ended up using Microsoft's LightSwitch, which was even simpler to implement than Naked Objects.  I have a similar need again, so I'm revisiting Naked Objects.

**Comment by richardpawson** [comment]
Good to hear, and I hope NOF works well for you.  I quite liked Lightswitch  -  I was given a confidential preview of it by Microsoft -  but I think it has now been discontinued.  I thought it was technically good, but mis-conceived in terms of market placement.  They were after the so called 'end-user development' market. Some people wrongly perceive Naked Objects that way, but that has never been my intent.  NOF is intended for use by professional developers, but who want to focus their energies on programming domain logic not technical/systems logic.

**Comment by scascarini** [comment]
Tested student creation in Template NOF11. All works fine without any need for web.config tweaks.
