### ISSUE TITLE
Actions contributed to an object's direct collection, forces a load of the whole collection on execution.

### ISSUE THREAD

**Issue by VantageKR** [NakedObjectsGroup/NakedObjectsFramework#184]
Inspecting the generated SQL and queries, I've found that contributed actions cause the system to issue a query to the db to load all the entities of the type of the first parameter to the contributed action. One would imagine that it should only retrieve the selected (checked in the UI) list of those entities, but it loads everything and then passes on to the contributed action, the actual selected list of chosen entities to act on. This was discovered after bug tracking very slow response times for contributed actions where the number of same type entities that exist is very large, even though the number of entities available for selection, to act on, is very small.

Example would be if you are expanding a collection of instances of type C on an instance of class A, where there are say 10 to 20 items for C, but there are many other instances of A with their own collections of type C; the system seemingly incorrectly and redundantly issues a query to load all instances of type C instead of only loading A's instances of type C.

A workaround is to create a Choices0... method to only load A's instances of C, but ideally, the [ContributedAction] attribution to that first parameter of the contributed action should cause the system to NOT load anything except the small number of actual selected (and displayed) instances of type C, and those would per definition be only from the set of A's instances of type C.

To be more clear, if a Person entity has many Addresses, represented as a collection property Person.Addresses, then a contributed action defined in the Person class, say DeleteAddress, with first parameter [ContributedAction] IEnumerable<Address> addresses will cause all Address entities to be loaded when the DeleteAddresses action is invoked, although only the checked / selected Address instances will be passed to the action (as expected).

If a Choices0DeleteAddresses method returning only the addresses for this instance of Person is created, the system invokes it instead of retrieiving all Address instances, and this can be verified by looking at the SQL Server query store.

This behaviour is encountered for contributed actions with only the one parameter for representing the selected items, and for contributed actions with additional parameters. It's not much work to create the Choices0... methods, but ideally the system should not even load all the instances, but only the ones from the selection?

**Comment by richardpawson** [comment]
I changed the title of the issue, because, as written, people might think that your issue happened on query-contributed actions, which it doesn't.

Although I was not previously aware of the point you made, I am not particularly surprised by it.  It has always been our position that _direct_ collections (multiple associations) should be kept small in arity  -  because they cannot be paged. If you open a collection on an object, all the members will be loaded, so it is not surprising to me that if you invoke an action on a selected subset of them then they will be loaded again by that action.

If you have large numbers of associated objects then these are best handled by indirect associations i.e. actions on the object to return the associated objects, which may then be returned as IQueryable and hence paged.  Performing actions on selections should then work the same way as regular queryable-contributed actions.

**Comment by VantageKR** [comment]
Hi Richard,

Thanks, and good point: you are right and I'm not talking about query contributed actions.


"It has always been our position that direct collections (multiple associations) should be kept small in arity - because they cannot be paged. If you open a collection on an object, all the members will be loaded, so it is not surprising to me that if you invoke an action on a selected subset of them then they will be loaded again by that action."

In my case, all of the entities of the same type as the collection items are loaded - not only the ones associated to the parent entity.

For example, we have an entity Table, with a collection Columns of entity type Column members.

When we view a particular Table entity, and open it's Columns collection, if we then select 2 or 3 individual Column entity instances to serve as input to a contributed action, all, as in all Column entities, for all Table entities in the db (everything, not only the Table entity being viewed) are loaded (in the background, not visible in the UI), and then the particular invoked contributed action executes with the correct 2 or 3 Column entity instances as input.

However, the loading of ALL Column entities in the database takes a while, and hence the delay until the result of the contributed action shows up.

As said, if I add a Choices0... method to only return this.Columns, then things are far faster since that query selecting ALL existing Column instances from the db is no longer visible in the query store. Instead it is replaced by a query with a WHERE clause limiting the Column entityes to return to the particular Table entity instance at hand.

Hope that makes better sense?

The solution with the Choices0... method is workable, but ideally, should we not be only loading the 2 or 3 Column entities rather than all 10 or 20 Column entities associated with the Table entity instance?

Note that the Choices0... method does not produce a selectable list of options for the first parameter - exactly what we want, so nothing wrong there - since the Column entities to act on is already selected in the UI by clicking the checkboxes.

Regards,

Kerneels


On 09/01/2020 10:20, Richard Pawson wrote:

I changed the title of the issue, because, as written, people might think that your issue happened on query-contributed actions, which it doesn't.

Although I was not previously aware of the point you made, I am not particularly surprised by it. It has always been our position that direct collections (multiple associations) should be kept small in arity - because they cannot be paged. If you open a collection on an object, all the members will be loaded, so it is not surprising to me that if you invoke an action on a selected subset of them then they will be loaded again by that action.

If you have large numbers of associated objects then these are best handled by indirect associations i.e. actions on the object to return the associated objects, which may then be returned as IQueryable and hence paged. Performing actions on selections should then work the same way as regular queryable-contributed actions.

**Comment by richardpawson** [comment]
> When we view a particular Table entity, and open it's Columns collection, if we then select 2 or 3 individual Column entity instances to serve as input to a contributed action, all, as in all Column entities, for all Table entities in the db (everything, not only the Table entity being viewed) are loaded (in the background, not visible in the UI), and then the particular invoked contributed action executes with the correct 2 or 3 Column entity instances as input.

I suspect you have something unusual going on in your implementation that you aren't telling us, or aren't aware of  -  because if what you describe was happening generally then, given the scale on which Naked Objects is used in Ireland, I think we would be in some trouble by now!

I suggest, as I have done on several occasions before, that you create an _ultra-simple_, _standalone_, two-class, spike where type A has a collection of type B, and where there are instances of B not associated with A.  Write a very simple collection-contributed action on A and establish whether that is retrieving all Bs (not just the collection).  If it is, then please submit the code, and the means by which you have verified that this is the case, and we will look into it.

If the standalone spike does not demonstrate the behaviour you are finding with your system, then you can start increasing its complexity to find the point at which you do see it.

**Comment by VantageKR** [comment]
Thanks Richard. You were right - it's definitely not a general bug but rather something specific to our use. I followed your advice and verified it for myself with a very simple example: it only loads what it needs to, not everything.

I'll alter the issue to rather ask if anyone encountered this before - I have no idea why this is happening.


On 09/01/2020 12:23, Richard Pawson wrote:

When we view a particular Table entity, and open it's Columns collection, if we then select 2 or 3 individual Column entity instances to serve as input to a contributed action, all, as in all Column entities, for all Table entities in the db (everything, not only the Table entity being viewed) are loaded (in the background, not visible in the UI), and then the particular invoked contributed action executes with the correct 2 or 3 Column entity instances as input.

I suspect you have something unusual going on in your implementation that you aren't telling us, or aren't aware of - because if what you describe was happening generally then, given the scale on which Naked Objects is used in Ireland, I think we would be in some trouble by now!

I suggest, as I have done on several occasions before, that you create an ultra-simple, standalone, two-class, spike where type A has a collection of type B, and where there are instances of B not associated with A. Write a very simple collection-contributed action on A and establish whether that is retrieving all Bs (not just the collection). If it is, then please submit the code, and the means by which you have verified that this is the case, and we will look into it.

If the standalone spike does not demonstrate the behaviour you are finding with your system, then you can start increasing its complexity to find the point at which you do see it.

**Comment by VantageKR** [comment]
So as the above explains, it's more a matter of this behavior happening on our implementation. Anyone seen something similar before perhaps?
