### ISSUE TITLE
Explicit + private implementation of IViewModel methods causes reflection error

### ISSUE THREAD

**Issue by e-manual-goldstein** [NakedObjectsGroup/NakedObjectsFramework#194]
From: [ViewModelFacetFactory](https://github.com/NakedObjectsGroup/NakedObjectsFramework/blob/master/Core/NakedObjects.ParallelReflector/FacetFactory/ViewModelFacetFactory.cs)

```
if (!type.IsInterface && typeof(IViewModel).IsAssignableFrom(type)) {
           var deriveMethod = type.GetMethod("DeriveKeys", new Type[] { });
           var populateMethod = type.GetMethod("PopulateUsingKeys", new[] {typeof(string[])});

           var toRemove = new List<MethodInfo> {deriveMethod, populateMethod};

           if (typeof(IViewModelEdit).IsAssignableFrom(type)) {
               facet = new ViewModelEditFacetConvention(specification);
           }
           else if (typeof(IViewModelSwitchable).IsAssignableFrom(type)) {
               var isEditViewMethod = type.GetMethod("IsEditView");
               toRemove.Add(isEditViewMethod);
               facet = new ViewModelSwitchableFacetConvention(specification);
           }
           else {
               facet = new ViewModelFacetConvention(specification);
           }

           methodRemover.RemoveMethods(toRemove.ToArray());
       }
```

If either of the implementations of the "DeriveKeys" and "PopulateUsingKeys" methods on a particular class are private (rare occurence), the `deriveMethod ` and `populateMethod` variables respectively are set to `null` because e.g. `GetMethod("DeriveKeys", new Type[] { })` does not include private methods. The exception happens later on in `TypeUtils.MemberInfoEquals(...)`:
```

  if (lhs.DeclaringType != rhs.DeclaringType) {
      return false;
  }
```

(rough example, not tested)
```
public class Foo : IViewModel {
     
     string[] IViewModel.DeriveKeys()
     {
            return new[] { Key };
     }

     void IViewModel.PopulateUsingKeys(string[] keys)
     {
           Key = keys[0];
     }

     public string Key { get; set; }
}
```

**Comment by richardpawson** [comment]
I don't understand? What is the rationale for C# allowing you to specify that Foo implements IViewModel and yet Foo does not in fact offer the two public methods defined in the interface? (I didn't believe this would even compile - until I just tried it!)

And even though C# does allow this, why would you want to write your view model that way?

I can't think of any good reason why NOF should support this idiom.

**Comment by e-manual-goldstein** [comment]
I fully agree. It's a very odd feature of C# to be permitted (for some reason) to fulfil the contract of an interface using otherwise inaccessible methods. 

Regarding "writing your view model that way", I think this is a symptom of "Coding by IDE": When adding any interface to a class, one can take advantage of Visual Studio's "Implement all members explicitly" option, which by default seems to add the new methods in the format shown in the attached image
![explicit interface](https://user-images.githubusercontent.com/23556869/90799294-ec307c00-e30a-11ea-84a1-0c7c87558053.png)

Also can't think of any reason to support such an odd design, just wanted to highlight anyway.

**Comment by richardpawson** [comment]
OK, I've read up more on explicit implementation now. I see that the intent is to allow an object to implement more than one interface which define the same member but having different meanings.  It was probably added in anticipation of the more recent feature to allow interfaces to define concrete methods - which is multiple-inheritance in all but name!  I also recall that VB.NET had explicit implementation from the outset - although it worked slightly differently, by allowing the name of the method to be changed rather than making it private.

Anyway, I am grateful to you for pointing this out.  I've added a warning in the Developer Manual that the implemented methods on IViewModel must be public (and you should therefore avoid using explicit implementation),.
