### ISSUE TITLE
Access to Now/Today via IClock service

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#203]
Requires:

- Registration of Clock (implementation of IClock) service, found in NakedFunctions.Service

**Comment by scascarini** [comment]
Note on parameter indices. The code in SpecialOffer_Functions has parameter indices ignoring the initial 'this' parameter. I thought this was a bit confusing so at the moment the index used is the actual parameter index - eg 1 and 2 is correct for the example code.
