### ISSUE TITLE
AW demo: Sales_MenuFunctions.Menu

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#205]
Requires:

- Recognise NakedFramework.Menu.IMenu & IMenuFactory (in addition to NakedObjects versions)
- mark the NakedObjects namespaced versions of those two types (now found in NakedFramework.PM) obsolete

**Comment by scascarini** [comment]
IMenu etc  already moved to NakedFramework namspace as part of PM restructure.  NakedOBjects.IMenu  was completely removed.  Could be reintroduced as Obsolete but I think it's easier to not. Can be discussed.

**Comment by richardpawson** [comment]
For the time being we will leave IMenu & IMenuFactory in the NakedFramework namespace, and only consider 'doubling up' (for backwards compatibility) if a proven need arises.
