### ISSUE TITLE
[Edit] attribute

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#206]
Causes a function to be accessible (in RESTful API)  via a PUT method.

**Comment by richardpawson** [comment]
Implemented, and tested at RO API level. Not practical to test via UI until #211

**Comment by richardpawson** [comment]
To discuss.

I am leaning again towards this attribute resulting in a marker going into the RO, and having the function accessed via POST and _not_ PUT.  Because functions for editing an object might well result in other side effects such as a recorded action, and even the action was idempotent, the advantage (to the user) in making it a PUT rather than a POST is very limited.

**Comment by richardpawson** [comment]
I am re-opening this one because I would like to change the way it works. Previously we had said that this attribute would cause the function to be accessed via the Http PUT method, and that this would be all the hint provided to the client. I have had had a residual concern about this. My current view is:

- If a function is marked up with [Edit]  AND
- It returns only an IContext  AND
- The parameter(s) correspond to properties (on the type to which it is contributed) both in type, and in name (except for casing)

Then...

- It should still be a POST (it might, after all be updating the ModifiedDate anew each time it is called and/or adding a RecordedAction )
- The actions should have in its RO `extensions` a value indicating the name(s) property(ies) to which it should be associated on the client. e.g.:
`x-ro-nof-editProperties: ["First Name", "Last Name"]`
- When invoked, the current value(s) of the property(ies) should be automatically supplied as the default value(s) on the parameters without the need to specify that in code. 

Apart from the change from PUT (back) to POST, my other reasoning for this change is that in the previous pattern, the onus was put on the Client to determine the match-up of names and types, which seems wasteful. This new pattern does more of the work in the reflector.

**Comment by scascarini** [comment]
explicit defaults via actions or annotations take priority, the reflector generates a warning log in this case
