### ISSUE TITLE
Implementation of IPrincipalProvider

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#239]

**Comment by richardpawson** [comment]
IPrincipalProvider is defined in the NakedFunctions.PM - as a well-known service like IClock and IGuidGenerator.

(There is an extension method - _CurrentUser_ - for the context that uses this service.

**Comment by richardpawson** [comment]
Calling the extension method on (IContext) CurrentUser when there is no user logged on (as in the AW demo) results in a null reference exception being thrown.  

My preference would be that it would return null. But can you cross check against against the corresponding function on NOF IDomainObjectContainer?

**Comment by scascarini** [comment]
It is the same code as the DomainObjectContainer. I'll take a look

**Comment by scascarini** [comment]
The error I get when running the test code is caused by calling unrecognised code inside a LINQ to entities expression 

`NakedObjects.Facade.GeneralErrorNOSException: LINQ to Entities does not recognize the method 'System.Security.Principal.IPrincipal CurrentUser(NakedFunctions.IContext)' method, and this method cannot be translated into a store expression.`

**Comment by richardpawson** [comment]
Yes - that would be a problem. But I was testing on a much simpler, tempororay method that didn't involve LINQ:

```
//Bogus method with signature that will mean access using GET on RO
public static Employee TestPrincipal(IContect context) {
  IPrincipal p = context.CurrentUser();
  return null;  
}
```

The call to .CurrentUser() throws a null ref exception. Presumably this is because  there is no user logged on to the AW app. But equivalent code in the NO version of AW does not throw an error:

```
        [NakedObjectsIgnore]
        public virtual Employee CurrentUserAsEmployee() {
            IQueryable<Employee> query = from obj in Container.Instances<Employee>()
                where obj.LoginID == "adventure-works\\" + Principal.Identity.Name
                select obj;

            return query.FirstOrDefault();
        }
```

With no user logged in, this method just puts up a user message 'No Result Found' . So  Principal (which AbstractFactoryAndRepository just delegates to Container.Principal must be returning a Principal, even if the Identity.Name is empty.

**Comment by scascarini** [comment]
Running locally "context.CurrentUser() returns a ClaimsPrincipal,  Identity a ClaimsIdentity then the Name is null.  It's possible it's different on Azure.

**Comment by richardpawson** [comment]
I was running it locally when I got the error.
