### ISSUE TITLE
Saving a new object takes it to Edit mode

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#240]
Example on AW:  Create New Special Offer

When you hit OK it _does_ create and persist the new Special Offer, but returns it to the user in Edit mode. If you Cancel this you go back to the Special Offers menu (but can then see the created object via All Special Offers).

**Comment by scascarini** [comment]
All domain records should have

public override int GetHashCode() => base.GetHashCode();

**Comment by richardpawson** [comment]
All persistent domain types (in AW) now have:

public override int GetHashCode() => base.GetHashCode();
