### ISSUE TITLE
Implement grouping of actions (sub-menus) and properties

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#255]
In the NF model, the as-documented supported approach to specifying sub-menus will be through `MemberOrder `e.g.

```
[MemberOrder("Sales", 5)]
[MemberOrder("Sales_Promotions", 3)]
```

The underscore indicates the sub-menu hierarchy, so the second example above specifies a second-level sub-menu.

Note that this optional string property (which now has the parameter name `grouping`) can simply be output as the `x-ro-nof-menuPath` extension on the RO representation.

If the `grouping` parameter is specified on `MemberOrder` for a _property_, then an equivalent `x-ro-nof-propertyGrouping` extension should be added to the property. This will currently not have any effect at the UI, but could in future be used to support a visual indication of property groups or e.g. a collapsible region, 

Note that there is not currently any ability to define the order in which sub-menus appear on the main menu.

Although the historical pattern of using `IMenu `& `IMenuFactory `will still work _for main menus_, the documented pattern for specifying main menu layout will be `MemberOrder`. A new `MenuHelper.GenerateMenus` method (implemented in the _NakedFramework_ PM) will generate the `Func<IMenuFactory, IMenu[]>` from a set of types and avoid the need for the application programmer to touch, or even see, `IMenu `or `IMenuFactory`.  This helper will be used in all documentation, Template projects and examples e.g.: 

`builder.MainMenus = MenuHelper.GenerateMenus(AWModelConfig.MainMenuTypes());`

 avoids the need for the programmer to see or touch IMenu

**Comment by richardpawson** [comment]
This is now working for object actions, but not for main menu actions

**Comment by scascarini** [comment]
Missed it was supposed to work on menus too :(
