### ISSUE TITLE
Small changes to RESTful API

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#268]
I think that the implVersion should be changed to say e.g.

`implVersion: "Naked Objects 11.0.0" `

OR

`implVersion: "Naked Functions 12.0.0-alpha01"  `

(the name of the server framework being the new).

Secondly, we should review the data held for optional capabilities, which currently has:

`protoPersistentObjects: "yes"`

So this might need to be gleaned from some sort of 'Framework config' or spec.

Thirdly, for both NO and NF, if there happen to be no Services (which there never are in NF), then the Services property on the Home representation should not be rendered. It just avoids the distraction (for NF users) of 'what are services?'.  Also, I think that in NO if you have not registered _any_ services - the reflector throws an error anyway?

**Comment by scascarini** [comment]
For teh moment, until NO and NF are properly decoupled the server  is a composite and so will show (eg) Naked Objects 12.0.0-alpha01, Naked Functions 12.0.0-alpha01

**Comment by richardpawson** [comment]
Gone as far as we can for now. Not appropriate for Selenium testing, so closing.
