### ISSUE TITLE
Break up the Client build project on Appveyor

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#272]
The current project is both long (40+ minutes) and brittle. I suggest breaking it up e.g. into three:

- Build client and run unit tests on the client code. Run only when client code is changed. Deploys client to the web server.

- Naked Objects Selenium tests. Potentially run when Naked Objects Server, OR the AW.NO demo code is changed. 

- Naked Functions Selenium tests. Potentially run when Naked Functions Server, OR the AW.NF demo code is changed

**Comment by scascarini** [comment]
done
