### ISSUE TITLE
Reinstate option to assign background colours to types, randomly

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#280]
In an earlier prototype of the SPA client, we had this option and I would like to reinstate this option.

The idea was that each domain type would be assigned a colour (background colour, and link colour) from a limited palette, at random, but such that the type would always be assigned the same colour, each run. As I recall, this was done by making a Hash of the fully-qualified type name, modulo the palette size.

By default this option would be switched on, but may easily be switched off. Even when switched on, any more specific mapping of type to colour should override the randomly assigned colour.

**Comment by scascarini** [comment]
To allow random colour allocation add 
"randomMaxIndex": <number> 
to "colors" config in config.json.  A random color number from 1 to randomMaxIndex will be allocated to each type. Other config takes priority. Either no "randomMaxIndex" key or a value of 0 will mean no random allocation. Random values are cached for the session.
