### ISSUE TITLE
Write small test app that used byte[] for EF Concurrency Check AND for our own [Versioned] field

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#283]
This has become important because `byte[]` is now the recommended type for EF ConcurrencyCheck field. So we should be able to support it for use as the [Versioned] field also. Need to think about its presentation format (although it might typically be Hidden).

**Comment by scascarini** [comment]
byte[] has always been supported on server as value type. 
RO supports blobclob. 
option to include blobclobs in RO as properties now settable (was always false).

**Comment by richardpawson** [comment]
That there should be no issue using a byte[] property with [Versioned] for (our long term) concurrency checking – from the server perspective.

 

From a client perspective, to work with [Versioned] the property value would need to be passed up to the client, so it could not be [Hidden]/[Ignored]. But how would this be rendered?  Do we need to arrange for the client to render a byte[] property as a single number? Or in the standard IP address form e.g. 0.0.14.3.217?

 

Let me know thoughts and I’ll write a new (Client) ticket.
