### ISSUE TITLE
Redundant calls to IsVisible

### ISSUE THREAD

**Issue by e-manual-goldstein** [NakedObjectsGroup/NakedObjectsFramework#290]
https://github.com/NakedObjectsGroup/NakedObjectsFramework/blob/6e2986ece065c4ce670ff2a7ca0f8c292fcc753c/NakedFramework/NakedFramework.Facade.Impl/Impl/FrameworkFacade.cs#L209

In the GetPropertyInternal method on the FrameworkFacade class, if the "onlyVisible" parameter's value is "true", then the selection of property specs is filtered down by calling the IsVisible method on each spec (and resulting in the execution of any associated "Hide..." methods. 

However, the results of this filtration are then further reduced to either 1 or 0 by matching on "propertyName" in the SingleOrDefault method. If the number of results will ultimately always be 1 or 0, then the name matching could feasibly be done first and only then would the "IsVisible" method be called on that result. This way, the IsVisible method is only called on the properties that we are interested in.

**Comment by richardpawson** [comment]
Fixed in NakedObjects.Server 11.0.1 (and also in the active branch)
