### ISSUE TITLE
Add a class to an action (Input) to indicate whether it generates dialog or is a direct action

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#292]
My immediate use-case for this is Selenium testing, but it would be useful to allow different presentations.

(e.g. back on older NOF UIs, an action that took params - i.e. created a dialog - was rendered with an ellipsis, as originally used on the Mac and Windows UIs).

**Comment by scascarini** [comment]
action input tag has "dialog"  or "direct" class added as appropriate
