### ISSUE TITLE
Add [CreateNew], [Edit], & [DisplayAsProperty] attributes into Naked Objects

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#295]
These attributes exist, and are implemented (as far as the  RESTful API) in Naked Functions. We need them to work on Naked Objects in the same way (from v12) also.

Where practical, these attributes should inherit from a common abstract attribute in the NakedFramework.PM, and, again where practicable, their implementations to be at Framework level also.

**Comment by scascarini** [comment]
For testing
