### ISSUE TITLE
Couldn't find screenshots of UI

### ISSUE THREAD

**Issue by wite27** [NakedObjectsGroup/NakedObjectsFramework#297]
Hi! I looked throught repo and docs and I couldn't see any examples with screenshots of how UI looks out of the box (angular application in particular). Are there any? :)

**Comment by richardpawson** [comment]
There is a very simple demo app here: http://academyspa.azurewebsites.net/   where you can view the basics of the default UI.

Please note that on this site it can take several seconds to get going (i.e. until the main menus appear), and be slow for the first couple of retrieves. After that it is reasonably responsive. But slowness is entirely down to the specific (low-grade) Azure deployment and rare usage:. In a proper deployment, both Naked Objects and (currently in Beta), Naked Functions, are very fast.

**Comment by richardpawson** [comment]
You can also browse the RESTful API of the server for that app directly, here: http://academyrestfulapi.azurewebsites.net/  (provided you have JSONView or some other JSON formatter in your browser).  It's fully HATEOUS so you can get to the whole functionality of the app by following links and e.g. each Action representation will tell you exactly what parameters must be provided and in what format to invoke them.

**Comment by richardpawson** [comment]
The default UI can be re-styled using CSS. Or you can customise it more deeply using Angular.  The client is built from multiple layers, so most people only customise the topmost layer (Gemini) concerned with presentation, using all the underlying packages (to access and interpret the RESTfulAPI) unmodified.

**Comment by wite27** [comment]
Great, thanks!
