### ISSUE TITLE
File upload timedout

### ISSUE THREAD

**Issue by brentvee** [NakedObjectsGroup/NakedObjectsFramework#3]
Hey Richard,

I'm having an issue. I'm not sure if its NOF related or not.
I'm using a FileAttachment as an Action parameter and doing some rather intensive processing on the data therein.
My action starts and the code executes but after about 10-15 seconds a popup appears saying "Timeout - File upload timedout"
I tried this with a tiny and a large file, both resulting in the same error.
Is this more related to MVC or a NOF issue?
Regards

**Comment by richardpawson** [comment]
I've no reason to believe it is a NOF issue based on the limited information given  -  you'll need to do some further investigation and testing.

**Comment by brentvee** [comment]
From what i can tell there is a sql timeout exception happening during the `EntityObjectStore.EndTransaction` method when `RecurseUntilAllChangesApplied(1)` is executed
