### ISSUE TITLE
Get [Edit] attribute working on Naked Objects

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#302]
For the property

`public int Quantity `

Naked Objects will recognise:

```
[Edit]
public void ModifyQty( int quantity) //i.e. the param name must match, the method name need not necessarily.
```

We have agreed that (in Naked Objects) the [Edit] attribute will not be recognised for contributed actions.

**Comment by scascarini** [comment]
Removed support for contributed Edit methods because setting the default value for the parameters would require significant development effort (the value needs to come from the contributed-to object which is not currently available in the context of the default value facet).
