### ISSUE TITLE
Address remaining log WARNings on NF AW server.

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#305]
I have eliminated a good number of the log-warnings from the NF AW server project, but quite a few remain, which I don’t get or can’t resolve.

1)	There are several warnings relating to a couple of [Edit] methods where it appears to be protesting about too many parameters. Is there a limit?

2)	I think that in Naked Objects, you could have an auto-complete method that returned a single instance of the type instead of an IQueryable  - used to allow you to look up the customer by the account number. Naked Functions does no recognise this.  If this is easy to add, I will add a ticket for this (N.B.  Not urgent as this is NF, not NO).

**Comment by scascarini** [comment]
1. There is an optimisation that binds in a delegate to call the method. This has to be done individually for each number of parameters so there is an arbitrary limit (7 I think). If you exceed this the method is called but by reflection.  We considered a limit reasonable as we don't want actions with large numbers of parameters.  If however in NF more parameters are reasonable then we can bump to a new  limit. 

2. Autocomplete should work same way in NF as NO (ie the code is there to return a single value) if it doesn't work it's a bug and I will investigate

**Comment by scascarini** [comment]
Added tests for autocomplete returning single value - but seems to work OK.

**Comment by scascarini** [comment]
Parameter warning to be done under #308

**Comment by richardpawson** [comment]
The remaining WARNs are now all examples of functions with >6 params.  I should follow the given advice and seek to reduce this. I think they are all examples of functions to create new objects, and were written before the [CreateNew] functionality was added.  I should therefore reduce all these functions to asking only for the properties _absolutely required_ to create the new type, and then rely on [Edit] methods for the rest. (This will break quite a few existing Selenium tests, though).
