### ISSUE TITLE
AutoComplete returning a single domain instance rather than a queryable

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#307]
Naked Functions should recognise an autocomplete method that returns a single instance of the required type, rather than an `IQueryable`, and apparently there are tests for this.

However, on AW NF model I am getting a WARN in the log saying that the method `AutoComplete0FindOrders `(on Order_MenuFunctions) is '`not matching expected signature`'.  I can't see anything else wrong with it.

Another, example that is still generating a log WARN is `AutoComplete0OrdersForCustomer `(also on `Order_MenuFunctions`)

**Comment by scascarini** [comment]
This is actually working - the log is because it looks twice first time for a function returning a queryable second time an instance. The log is for the first search not finding the expected signature. I will make it only log the second search.
