### ISSUE TITLE
2. Create separate deployable and Selenium test job for Legacy on Appveyor

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#341]
The deployable test project is new `NakedLegacy.Rest.App.Demo`

The Selenium test project is `NakedLegacy.Selenium.Test`

**Comment by scascarini** [comment]
Server is at https://nakedlegacydemo.azurewebsites.net/
Client is at https://nakedlegacytest.azurewebsites.net/gemini/home
Selenium build https://ci.appveyor.com/project/scascarini/nakedobjectsframework-oqowd
