### ISSUE TITLE
17. Recognise IMemberOrderAttribute and other attributes defined by interface.

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#365]
Drop direct recognition of the `MemberOrder `attribute defined in LegacyPM, and instead recognise _any attribute_ that implements `IMemberOrderAttribute` (defined in Legacy.PM):

```
public interface IMemberOrderAttribute 
{
   public int Order {get; }
}
```

In a similar vein, recognise the following interfaces, corresponding to standard Naked Objects equivalents (define properties as appropriate - but ensuring all interfaces define different property names as one attributed might implement multiple such interfaces).

```
IMinLengthAttribute
IMaxLengthAttribute
```

**Comment by scascarini** [comment]
Only Maxlength done as no ro extension for min length
