### ISSUE TITLE
22. Empty entry-fields need to be represented as Value Holder instance when calling any About and/or Action method

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#372]
The current (framework) behaviour is that if the user does not type a value into a field then the corresponding parameter in the `AboutProperty `or `AboutAction `method is supplied with a null.  

The requirement is:

- When an `Action` method is called, each value holder type parameter is supplied as an instance of that type, never as null.
- When an `AboutAction `method is called in **Valid** mode, each value holder type parameter is supplied as an instance of that type, never as null.
- When an `AboutAction ` method is called _in any other mode_ the value holder parameters (as, indeed any reference type parameters) can, and preferably _should be_ null, since there cannot be meaningful values to provide and programmers should not be making use  of those parameters.
- Similarly for `AboutProperty `methods.

It is up to the Value Holder implementation to decide how to represent itself when asked to _parse an empty string_. It appears in legacy AppLib code that some value holder have a `boolean IsEmpty` flag.

**Comment by scascarini** [comment]
This relies on valueholders having a default no parm constructor that creates the valueholder 'empty'.
