### ISSUE TITLE
28. Enhancements to IContainer

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#378]
Add these properties/methods and use them in the system:

```
void AddMessageToBroker(string message)
void AddWarningToBroker(string message)
void ClearWarnings()

bool IsPersistent(object obj)();`

IList<Type> AllTypes()  

Resolve()  (as per Naked Objects).

T SystemService<T>
T DomainService<T>  //Replaces the previous Repository method
```

**Comment by scascarini** [comment]
A couple of questions 
1. I assume AllTypes returns effectively the list of types passed to the reflector in config.  Should we return this as an IList<Type> ?
2. Info and warning messages are arrays of strings - when 'get' the property do you want the last message  or all the messages comma separated, or ?

**Comment by richardpawson** [comment]
Have answered these and made some other changes in the ticket #378
