### ISSUE TITLE
35. Wholesale changes to (Legacy) namespaces & assembly names

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#389]
1. _All_ use of `NakedLegacy `in _namespaces_ to be changed to `NOF2`. 

2. `NakedLegacy.ProgrammingModel` to be renamed NOF2.ProgrammingModel for both the project/assembly names and package name.

3. `NakedLegacy.Reflector` to be renamed to `NOF2.Reflector` for both the project/assembly names and package name.

(Optional). I don't care so much about use of '`NakedLegacy`' in test and demo code, but if straightforward it would probably be cleaner to use '`NOF2`' throughout.

**Comment by scascarini** [comment]
build green
