### ISSUE TITLE
Issue saving a transient with a reference property

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#398]
**This _might_ be connected to #396** 

I _think_ this is a bug (but could be my code of course). It can be demonstrated in the new template solution: `NOF2.Template.Server.Sln` - from two actions currently on the **Students** menu:

(If starting from scratch, create a new `Teacher` object first, from **Teachers** > **Create New Teacher** )

- **Create New Student1** gives a dialog. Specify a **Name** and **Year Group** (integer) and drag in the `Teacher `object into **Tutor**. All works fine.

- Now repeat this, but leave the **Tutor** empty. The returned `Student `shows an **Untitled Teacher** reference - which has been somehow created unwittingly. (Viewing **All Teachers** shows this). I think this only happens to work because `Teacher` has no mandatory fields except for the database-generated `Id`. 

- From any of the existing students, **Edit** and remove the `Teacher `reference from the Tutor field, and **Save**. This works fine, showing that the property can be empty. 

- **Create New Student2** takes no parameters, but returns a transient `Student`. This fails, with an error from our framework, whether you provide a **Tutor** or not.

**Comment by scascarini** [comment]
1. We were not discriminating between valueholders and reference objects hence the 'placeholder' - fixed.
2. Student doesn't have a ActionSave however the error was not being handled properly. Now sent up to client. Tested OK with ActionSave.

**Comment by richardpawson** [comment]
Stef - please add unit/end-end test for the _first_ case, then assign back to me for a Selenium test
