### ISSUE TITLE
Move NOF2.PM down to .NET 3.5

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#399]
Currently NOF2.PM depends on NakedFramework.PM ,and I am reluctant to downgrade the latter.  

However, the _only_ use of NakedFramework.PM in NOF2.PM is the use  of  the `WhenTo `enum. I think it would be better to just duplicate this in NOF2 and then remove dependency on NakedFramework altogether if possible.

(Note that once the switchover is made, domain projects can then move up to .NET 6.0)

**Comment by richardpawson** [comment]
This is to maximise compatibility with legacy application code

**Comment by scascarini** [comment]
We wont be able to build anything before .net 4.5.2 on VS2022
