### ISSUE TITLE
Option to display a URL property as a reference link

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#439]
If a `string `property on an object contains a URL then it may be marked up with a (new) `UrlLlink` attribute, which has two optional fields:

- `bool alwaysOpenInNewTab`  defaults to `false` but if set to `true`, will always open in a new tab, whether left- or right- clicked.
- `string displayAs` allows the link (for a property this is) to be displayed with a friendly title. If not specified the title is shown as the URL itself.

Example of use:
```
[UrlLlink("Start")]
public string Task {get; init;)

```
Applied to a string property, the attribute causes the value to be rendered just like a reference object, and when clicked takes you to the URL.  Right-clicking takes you to the URL in a new browser tab (unless `alwaysOpenInNewTab `is true in which case it doesn't matter whether you left or right click).

Suggested code for the _abstract_ attribute (should be concrete in both NO and NF PMs):

```
    [AttributeUsage(AttributeTargets.Property)]
    public abstract class AbstractUrlLinkAttribute : Attribute {

        public AbstractUrlLinkAttribute() { }

        public AbstractUrlLinkAttribute(bool alwaysOpenInNewTab) {AlwaysOpenInNewTab = alwaysOpenInNewTab }

        public AbstractUrlLinkAttribute(string displayAs) {DisplayAs = displayAs }

        public AbstractUrlLinkAttribute(bool alwaysOpenInNewTab, string displayAs) : this(alwaysOpenInNewTab) { DisplayAs = displayAs }

        public bool AlwaysOpenInNewTab { get; }
        public string DisplayAs { get; }

    }
```

**Comment by scascarini** [comment]
Implemented and working on properties. Unfortunately RO doesn't recognise actions returning strings. So this doesn't work on actions without making changes to RO.

**Comment by richardpawson** [comment]
I've removed the requirement for applicability to actions. However, in the light of this please remove the `AttributeTargets.Method` from the attribute.

**Comment by richardpawson** [comment]
Completed
