### ISSUE TITLE
Enable validation for FileAttachments/Images

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#442]
The following (in Naked Functions - but same probably applies to Naked Objects too) does not currently work, and it would be useful if it did:

        public static IContext Foo(
            this Bar bar, 
            FileAttachment newAttachment, 
            IContext context) =>  <implementation>

        public static string ValidateFoo(
            this Bar bar, 
            FileAttachment newAttachment,
            IContext context) =>
            newAttachment.MimeType != @"text/html" ? "File must be of mime type text/html": null;

(Validation could also be used to limit file size, for example)

**Comment by scascarini** [comment]
This should have worked but a bug in the REST API (the FileAttachment parameter is returned as part of the error response and the encoding was failing)  was obscuring it. 

Bug fixed and tested. Tests added for File Attachment validation.
