### ISSUE TITLE
An empty property of type FileAttachment displays as 'No Image'

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#443]
I know that Image and `FileAttachment `have a great deal in common. So if this needs to be a single message (or its just easier that way), then perhaps change it to 'Empty' - or even just blank. 

Please also at the same time, add a class to the FileAttachment html (around the displayed filename) such that it could be rendered like a reference property (same as you have recently done for UrlLink #439

**Comment by scascarini** [comment]
now it should say 'No Image' if the mimeType is jpg, gif or octet-stream otherwise it will say 'Empty'. If there is an attachment and it has a title we will display that instead.
