### ISSUE TITLE
New attribute to hide things in generic client (but not from RO API)

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#445]
If applied to a property, or an action, the property/action would still be accessible via the RO API (unless made invisible by other means inc. authoriization) but would not be rendered visible in the default client.

Obviously, this attribute does not provide any security it is just a cosmetic tweak - intended for use on methods/properties that a custom client might access (via RO API) but are not intended for direct display.

I think it is better to make this a separate attribute `HideInClient` because it really doesn't have anything in common with the existing [Hidden] attribute. It is effectively just a well-known `PresentationHint`.

Suggestion: could this (and possibly some more) simple attributes just be made sub-classes of some common Framework-level attribute possibly `PresentationHint `itself?

**Comment by scascarini** [comment]
As implemented this is just a subtypes of PresentationHint. This reuses all the existing PresentationHint code but does mean  you can't have a HideInClient and PresentationHint on the same thing. It will fail in reflection - multiple same type custom attributes.

**Comment by richardpawson** [comment]
Completed
