### ISSUE TITLE
RunWeb

### ISSUE THREAD

**Issue by waynerochford** [NakedObjectsGroup/NakedObjectsFramework#47]
Hi,

I'm learning NOF from the ground up following the user manual. However when I run the command in the nuget console `Install-Package NakedObjects.Mvc-FileTemplates -Version 7.1.1`

The **RunWeb.cs** file is not visible.

I've tried everything to generate the **RunWeb.cs**, but so far no luck.

Thanks,

Wayne.

**Comment by richardpawson** [comment]
Wayne

If you are learning NOF from scratch, you should definitely be using version 8, and not version 7.  (And in fact 7.1 was a withdrawn version anyway.)

Make sure you have the 8.0 user manual.  There's a link to it on the ReadMe file, which is also shown at the bottom of the home page on this repository  There is also a link to a .zip of a minimal 'Template' application, which is the best way to get started.

**Comment by waynerochford** [comment]
Got it

Thanks Richard :)

- Wayne
