### ISSUE TITLE
Config option to alter left/right click behaviour

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#490]
This is a follow-on from #479. It is _possible_ that this new idea has also already been implemented from the outset, so need to check!

The current behaviour is:

- Left click means open result in the _same_ pane that you are on.
- Right click means open result in _opposite_ pane (where single pane is deemed to be 'left pane')

Despite having designed this, I find myself frequently getting it wrong. I now think that it might be better (and certainly easier to describe) as:

- Left click means open result in the `left `pane (stays with existing single or twin pane presentation).
- Right click means open result in the `right `pane (always results in twin pane presentation).

I think the best approach would be to make this a configurable option, for these reasons:

- Avoids breaking all existing Selenium tests
- Allows customer (not individual user, though) to go either way. 

But I would like new option to be made the default (and in MetalUp.Express) - just change it for the deployment used by the Selenium tests.

**Comment by scascarini** [comment]
Need to release 14.1 to see in express

**Comment by richardpawson** [comment]
Confirmed in Express
