### ISSUE TITLE
Reflector: recognise nullable types as being implicitly optional for entry purposes?

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#493]
At the moment, optionality is determined only by the `[Optionally]` attribute.

If it is possibly to pick up nullability of a type (domain entity type or value type)  at runtime, then the reflector could add the optional _facet_ automatically. If the [Optionally] attribute exists in code, this should be logged (as `Info:` ?) that it is redundant.

**Comment by richardpawson** [comment]
You are right to raise the concern.  I think that as long as we are testing this properly then if the compiler changed its approach then we could pick up the error.

So one solution is to make this a configuration option: `nullable parameter type is automatically treated as optional`. If a compiler change meant this could no longer be supported then we can simply remove that config option - which would bring the change to the attention of the application developer.

**Comment by scascarini** [comment]
Needs 14.1 release to test in express
