### ISSUE TITLE
Check actions that apply to selection from an internal collection in Naked Functions

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#495]
This arose from discussion of  #470. 

In Naked Objects, this capability is documented as: **How to create an action that operates on a selection from a collectio**n. (There is no mention of 'contributed' in this context). Given that such actions are instance_ methods on the object, there is no special treatment required for authorization.

Does this capability exist for Naked Functions. (There is no mention in the documentation). I don't see why they can't be. I am in no rush to have it, but would like to know if it does work or not.

**Comment by scascarini** [comment]
Tested - it works in NF (so perhaps should be documented?) 

When authorizing the function is treated as any other action on the object (ie the Authorizer for the owning object is called not the collection).
