### ISSUE TITLE
NakedObjects.Template application build errors

### ISSUE THREAD

**Issue by ericlobato** [NakedObjectsGroup/NakedObjectsFramework#63]
I just downloaded the template of NOF8 and hit F5. I installed previously the typescript 2 from microsoft. After hit F5 the nuget packages was restored but the build returned errors:

![image](https://cloud.githubusercontent.com/assets/12720147/21502554/d556e3a4-cc37-11e6-9168-ff30ce4db899.png)

**Comment by scascarini** [comment]
You need to target es5 that's the default did you change it?

http://stackoverflow.com/questions/12811034/targeting-es5-with-typescript-in-visual-studio#

**Comment by ericlobato** [comment]
Now I am having those errors:

![image](https://cloud.githubusercontent.com/assets/12720147/21532149/9519b926-cd34-11e6-85f9-3080316408c0.png)

**Comment by scascarini** [comment]
For some reason you don't sem to be picking up the lib.d.ts definition of parent. 

I'll take look when I get back to work. In the meantime you could work around with an 'any' cast. (<any>parent).history

**Comment by scascarini** [comment]
GitHub obviously doesn't like angle brackets - should be and any in angle brackets before parent in comment above
