### ISSUE TITLE
NOF cannot be installed under VS2013.

### ISSUE THREAD

**Issue by constructor-igor** [NakedObjectsGroup/NakedObjectsFramework#66]
Please, could you solve the issue or update sample?

![image](https://cloud.githubusercontent.com/assets/1849690/23517009/af3b0c54-ff77-11e6-9ed9-1f9e836ba381.png)

![image](https://cloud.githubusercontent.com/assets/1849690/23516992/9dd067f2-ff77-11e6-8efe-75c1b8009da1.png)

**Comment by richardpawson** [comment]
1. The error message is telling you that you need to upgrade your NuGet Client version in Visual Studio. This is not an issue with Naked Objects.
2. Your excerpt from the developer manual is, I think, Naked Objects 7.0.  That is now an obsolete version.  You should be using Naked Objects 8.0 (and we will shortly be issuing the first Beta of 9.0). See the NOF8 developer manual here: https://github.com/NakedObjectsGroup/NakedObjectsFramework/blob/master/Documentation/DeveloperManual.docx?raw=true
