### ISSUE TITLE
NOF7 error handling on IIS10 (incl. Azure App Service)

### ISSUE THREAD

**Issue by TomFox7** [NakedObjectsGroup/NakedObjectsFramework#67]
Most error handling in NOF7 is done by the [GenericControllerImpl.OnException()](https://github.com/NakedObjectsGroup/NakedObjectsFramework/blob/7.0/MVC/NakedObjects.Mvc/Controllers/GenericControllerImpl.cs) method, but additional special treatment is needed for http status code 500 (DomainException), 500 (base Exception) and 404 (not found).  

These surprising settings are necessary to pre-empt unwanted Ajax pop-ups:

* Web.Release.config: system.web customErrors mode="Off" with no redirects specified.  Note: Off is normally not recommended, so it is crucial to catch Application_Error events.
* Web.Release.config: system.webServer httpErrors errorMode="Custom" existingResponse="PassThrough"  with no path or responseMode specified.
* Handle and log the base Exception in Global.asax.cs by catching the Application_Error event, because otherwise the detailed error information page is exposed to end users.

Code example:

		private static readonly ILog Log = LogManager.GetLogger<MvcApplication>();

		/// <summary>
		/// Minimal handler for Http status code 500 Internal Server Errors in NOF7 only
		/// </summary>
		private void Application_Error(object sender, EventArgs e)
		{
			Exception exc = Server.GetLastError();
			Server.ClearError();
			Log.Error($"### MVC Application_Error:\r\n Type: {exc.GetType()}\r\n Message: {exc.Message}\r\n Trace: {exc.StackTrace}\r\n");
		}

Suggestions are welcome for improvements or alternatives, as an HttpNotFoundResult (404) only returns an empty result.  
Why not handle HttpNotFoundResult as another case within GenericControllerImpl.OnException()?
See also http://stackoverflow.com/questions/499817/what-is-the-proper-way-to-send-an-http-404-response-from-an-asp-net-mvc-action

**Comment by richardpawson** [comment]
Thanks for posting Tom.  We will look into this issue and provide a better fix if/when we do another release of NOF 7  -  but that is not currently scheduled.  Meantime, it sounds like you have a workaround.  I am also slightly puzzled: are throwing domain exceptions in normal operation of the system?  Could/should you be catching those exceptions within your code and perhaps just doing a Container.WarnUser instead?
