### ISSUE TITLE
Drag and drop styling

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#75]
(This is a bug in NOF9 rc1)

1. The red/green border styling on drag and drop is no longer working.  Looking at the html the 'dropping' class is not being added.

2. The styling of the object being dragged has changed  -  it has developed a graded tint, and is not the correct size.  Again, I suspect that an html class is missing/changed?

**Comment by scascarini** [comment]
complete

**Comment by richardpawson** [comment]
The red/green border styling is now working.  The translucent styling of the item being dragged is under the control of the ng2-dnd component styling.
