### ISSUE TITLE
Need consistent TimeSpan input (e.g. TimePicker)

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#77]
(This is an issued with RC1)

At present, Chrome renders a TimeSpan field with its own TimePicker.  This works well, but it is not picking up the default value (e.g. on AW  Shift class, Change Times action).  Conversely, IE is picking up the default value, but it is being rendered as a Date + Time string.

**Comment by scascarini** [comment]
complete
