### ISSUE TITLE
Different instance for same type

### ISSUE THREAD

**Issue by brentvee** [NakedObjectsGroup/NakedObjectsFramework#86]
Hey Richard,
I've just noticed some unexpected behaviour resolving a service from the container.
We have a scenario where a section of code uses ```Container.GetService<PeopleService>``` and another uses property injection ```public PeopleService PeopleService{protected get;set;}```.
Within the same request, these two services are two different instances.
I did a test and the same instance is returned within each way of resolving.
These two are the same instance : 
``` 
var ps1 = Container.GetService<PeopleService>();
var ps2 = Container.GetService<PeopleService>();
```
And these two are the same instance
``` 
public PeopleService PeopleService1{protected get;set;}
public PeopleService PeopleService2{protected get;set;}
```
But the four of them are not the same instance.
Is this expected behaviour?

**Comment by richardpawson** [comment]
Services are intended to be stateless (this has always been the policy and is clearly stated in the manual). In part this is precisely because there is no guarantee that in two different contexts you are getting the same instance.

**Comment by brentvee** [comment]
Ok thanks Richard.
Are there any plans for future NOF versions where you might support dependency injection using factories?

**Comment by richardpawson** [comment]
We have no such plans.
There's no reason why you can't inject a 'service factory' as a service now, and use that factory to obtain some other service by whatever mechanism you want and delegate to that in turn.  

(Though I have to say that I think that when working with any comprehensive framework like NOF, if you find yourself wanting to cut across its core design constraints you need to ask yourself whether this is really necessary and/or a good idea.  The more you find yourself fighting the framework the less benefit you are likely to gain from the framework).
