### ISSUE TITLE
NOF9 Template.Client troubleshooting

### ISSUE THREAD

**Issue by TomFox7** [NakedObjectsGroup/NakedObjectsFramework#87]
After initial success with the Template solution (following the Developer Manual), the .Client page index.html at http://localhost:5001/ now loads blank (no text nor icons), even though the json from the .Server at http://localhost:5000/ still works as expected.  
This issue followed updates to some 3rd party packages via NuGet.  Please recommend how to troubleshoot the Client.

Oddly the problem still exists with a fresh installation; perhaps Windows automatically configures some other machine setting?
More details from the Chrome console:
main.c06e4aa4a0ecbe286b9c.bundle.js:1 Unexpected token / in JSON at position 215
SyntaxError: Unexpected token / in JSON at position 215
    at JSON.parse (<anonymous>)
    at e.CPp0.t.json (http://localhost:5001/vendor.50bbc77fa8562acbf045.bundle.js:352:1979)
    at e.project (http://localhost:5001/main.c06e4aa4a0ecbe286b9c.bundle.js:1:168472)
    at e._next (http://localhost:5001/vendor.50bbc77fa8562acbf045.bundle.js:641:143125)
    at e.T14+.e.next (http://localhost:5001/vendor.50bbc77fa8562acbf045.bundle.js:406:36086)
    at XMLHttpRequest.a (http://localhost:5001/vendor.50bbc77fa8562acbf045.bundle.js:366:632)
    at t.invokeTask (http://localhost:5001/polyfills.34a3cae36254ed087563.bundle.js:36:8048)
    at Object.onInvokeTask (http://localhost:5001/vendor.50bbc77fa8562acbf045.bundle.js:188:6682)
    at t.invokeTask (http://localhost:5001/polyfills.34a3cae36254ed087563.bundle.js:36:7969)
    at r.runTask (http://localhost:5001/polyfills.34a3cae36254ed087563.bundle.js:36:3224)

**Comment by richardpawson** [comment]
Tom.  Just to clarify, when you say 'update to third party packages' via NuGet  -  are you referring to third-party packages that you are using (e.g. graphics?) or to third party packages that the NOF is dependent upon.  I assume the former -  as we use NuGet for the server side but not for the client side (which uses NPM) -  but could you be a bit more specific?  If so, is it possible that it updated further JavaScript packages that it needs, but NOF also needs?  If this is the case you probably need to switch to start building the NOF client (using Angular/CLI and NPM) to make sure that these two things are not trampling on each other.

Also, please confirm: are you saying that the out-of-the-box  template solution no longer works for you either (since these updates) ?

In terms of debugging the client, you can do this with breakpoints and inspections in the browser, but you would probably be better off debugging the TypeScript code using Visual Studio Code -  though again you need to be building the client that way.

**Comment by TomFox7** [comment]
Richard, to confirm: this issue is with the out-of-the-box Template.sln.  (BTW, I did amend some namespaces in App_start and also deleted "rest" from the appPath.  I ignored a prompt from VS2015 to use a newer release of TypeScript.)
For the moment I assume the issue is in the .Client, only because I do see the expected json on the .Server.  The Nuget updates were only of existing dependencies.
Curiously, I now cannot get a fresh install of the Template.sln to work, except on another machine.

**Comment by richardpawson** [comment]
Tom, can you clarify what the 'Nuget updates' is referring to, specifically.  You are saying that it was these updates that stopped it working?

**Comment by richardpawson** [comment]
Also  -  do you get the same error from different browsers?

**Comment by richardpawson** [comment]
Is the stack trace that you showed in your original post from the out-of-the-box template, or from your own app? If the latter, what trace do you get from the former?

**Comment by TomFox7** [comment]
Richard, I've just got a fresh Template.sln to work on the same machine (and I am recording all steps precisely under version control), so I will revert when I identify what causes the break. 
Latest insight is .Client success in Firefox Developer edition (v.55.0b14) and failure in Chrome (Version 60.0.3112.90).

**Comment by TomFox7** [comment]
Some happy news:
1.	Downloaded Template_NOF9.zip and extracted into a new folder under C:\Users\userName\Documents\Visual Studio 2015\Projects\NOF9001
2.	Ignored the VS2015 prompt to update the project’s Tools Version.
3.	Deleted C:\Users\ userName \Documents\Visual Studio 2015\Projects\NOF9001\.vs\Template\v14\.suo
4.	Solution>Restore NuGet packages
5.	Deleted “rest” from appPath in config.json
6.	VS menu Build>Clean Solution
7.	Optionally: Deleted the previous existing local database from …
8.	Ran in Chrome: .Server http://localhost:5000/ loads as expected. (The Chrome extension JsonView was already installed.), but .Client index.html loaded blank.
9.	 Template.Server>Properties>Web Project Url = http://localhost:5000/ and button ‘Create Virtual Directory’
10.	Template.Client>Properties>Web Project Url = http://localhost:5001/ and button ‘Create Virtual Directory’
11.	Reviewed C:\Users\Tom\Documents\Visual Studio 2015\Projects\NOF9001\.vs\config\ applicationhost.config: found appropriate updates of <site name="Template.Client" id="2"> and <site name="Template.Server" id="3">.
12.	Edited index.html (only cosmetic)
13.	Corrected namespaces under Template.Server/App_Start
14.	Deleted Template.Server/Template.sln, .build, .nuget, Template.Server/.vs and Template.Client/.vs folders. Closed and re-opened .sln. Cleaned and re-ran .sln in FirefoxDevEd (success).  .Client still fails in Chrome.
15.	Manage NuGet packages for solution:
16.	Updated ApplicationInsights packages
17.	Project ToolsVersion="14.0" in Template.Server.csproj and Template.Client.csproj
18.	Now works in both FirefoxDevEd and Chrome.
19.	Updated Microsoft.* AND System.* Packages.  Forced to re-start VS2015.
20.	Still works in both FirefoxDevEd and Chrome.
21.	Updated Common.Logging packages.
22.	Unhandled Exception in RestfulObjectsControllerBase.InlineDetailsInActionMemberRepresentations = false;
23.	Roll-back in version control.  Further news to follow later.

**Comment by TomFox7** [comment]
Despite the solution detailed above, the issue has now returned in both browsers.  The browser console stack trace appears to be the same as before.   Firefox DevEd is slightly more descriptive in the first line: "JSON.parse: expected double-quoted property name at line 6 column 40 of the JSON data".
