### ISSUE TITLE
NOF7 Documentation bug: DisplayName attribute not "using"ed into sample code

### ISSUE THREAD

**Issue by tedneward** [NakedObjectsGroup/NakedObjectsFramework#9]
In the section "Writing your first Naked Objects application", the CustomerRepository sample shows using the DisplayName attribute but with no corresponding "using" declaration to bring it into lexical namespace. Presumably this is the attribute from System.ComponentModel?

Additionally, it's not clear in this section whether this class is intended to be declared inside of namespace MyWebApp, MyWebApp.Models, or something else. This needs clarification.

**Comment by richardpawson** [comment]
Per my other comment, I will get this sorted in the manual.  Meantime:

Yes, that is the DisplayName from System.ComponentModel

Namespace for the domain model is not critical, provided that you are referencing CustomerRepository in NakedObjectsRunSettings.
