### ISSUE TITLE
Ability to render any (unmodifiable) DateTime property as a TimeStamp

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#91]
See also #90

It should be possible to achieve the same effect as adding ConcurrencyCheck, but without the obvious meaning of the latter.  This could be done, without extending the ProgrammingModel by using the following attribute (from System.ComponentModel.DataAnnotations):

`[DataType(DataType.DateTime)]`

**Comment by scascarini** [comment]
I think we already support this 
https://github.com/NakedObjectsGroup/NakedObjectsFramework/blob/7a76ebde6fe5bec52062778a045211ce4d8d54ab/Samples/AdventureWorksModel/Sales/SalesOrderHeader.cs#L291

**Comment by richardpawson** [comment]
Oops - and it is fully documented in the Manual, also!  I'm at least glad of consistency in approach.
