### ISSUE TITLE
NOF 9 and AccessTokens

### ISSUE THREAD

**Issue by brentvee** [NakedObjectsGroup/NakedObjectsFramework#92]
Hey Richard,
I'm busy setting up NOF 9 finally.
However my first hurdle is that the client is not sending up an accesstoken as part of the request header to the restfulapi server.
Did I miss this somewhere in the documentation?

We're using Identity Server for claims authentications.

**Comment by richardpawson** [comment]
The latest version of the NOF9 Developer Manual describes how to do authentication and authorization under NOF9.  I suggest you try out a simple standalone example first of all, and then make it work with your existing models.

**Comment by brentvee** [comment]
Hey Richard,
The manual states "It makes use of the Auth0 login service". 
We are not using Auth0 we are using IdentityServer. While both of them use OAuth standards they don't work the same way.
Using your template example with a modified config.json I can see you're appending the applicationName to the Url with a .js : 
```An error occurred when fetching client data for Lock: https://<our-identity-sever>/identity/client/testapp.js?t1503388718508 could not be loaded.```

We could use standard MVC to perform our redirects for logins but we need a way to store the AccessToken on the client-side to be injected into each angular http request.

**Comment by richardpawson** [comment]
You will need to implement your own Auth  and AuthHttp services and then bind them in using app.module.ts.  It should be reasonably clear from the code, by looking at how we did it for the Auth0.  e.g.:

```
{ provide: AuthHttp, useFactory: authHttpServiceFactory, deps: [Http, ConfigService, RequestOptions] },
{ provide: AuthService, useFactory: authServiceFactory, deps: [ConfigService, Auth0AuthService, NullAuthService] }
```
