### ISSUE TITLE
dotnetcore 2.0 support?

### ISSUE THREAD

**Issue by tedneward** [NakedObjectsGroup/NakedObjectsFramework#94]
Dunno if this is in the works already, but it would certainly be enjoyable if the server could be run from dotnetcore 2.0 (such as from a Docker container). Note that I have zero comprehension of how much work this would actually take--only that I know that's quickly becoming a request for a number of different .NET projects around the Internet. :-)

**Comment by richardpawson** [comment]
Thanks for the suggestion, Ted.  I, neither, have a sense of how much work that would entail, but we'll look into it.

**Comment by richardpawson** [comment]
Ted, after further investigation, I think it would be premature for us to explore going to dotnetcore.  The principal issue would be Entity Framework.  Although, there now exists an EF Core, according to the Microsoft documentation, it is not a full implementation of EF6 capabilities, and nor is it mature.  Ref: https://docs.microsoft.com/en-us/ef/efcore-and-ef6/

**Comment by tedneward** [comment]
That's where I wasn't sure what the workload would entail--moving over to dotnetcore itself wouldn't be too hard, from what I can tell, though there's a few assemblies that didn't quite make the move over or got transformed slightly. The EF story is not one that I'm all that sure about.

Which features of EF6 are missing from EF Core that you need?

**Comment by corku** [comment]
Hi, 
How should I approach NOF if my app targets ASP.NET Core 2.0?
Great framework and philosophy..BTW

Michael

**Comment by richardpawson** [comment]
Michael

We don't yet have any experience of running NOF under .NET Core  -  though it is something we want to do at some point.  As commented above, our main concern would be over compatibility at the Entity Framework level -  maybe this has since matured.

If you're willing to operate at the leading edge, you could try re-compiling the NOF, targeting .NET Core and seeing how far you can get - but no promises!

**Comment by runxc1** [comment]
So with the release of EF Core 2.1 and 2.2 it would seem that most of the needed features such as lazy loading are now baked into EF Core.    The non core version of Entity Framework is no longer going to be receiving any new features (such as spacial queries which they are bringing to EF Core) .   It would seem that this would be a great project to see on .Net Core.

**Comment by richardpawson** [comment]
Thanks for suggestion. FYI we are now hoping to do a .NET Core 3.0 branch later this year.

**Comment by richardpawson** [comment]
11.0.0-rc01 has moved to .NET Core 3
