### ISSUE TITLE
Malformed arguments when trying to invoke a service action

### ISSUE THREAD

**Issue by Koenyn** [NakedObjectsGroup/NakedObjectsFramework#96]
I'm trying to invoke an action on the RestfulObjectsController from an angular app. I can hit the controller fine, but when it is executing base.GetInvokeOnService I get the following response:
`
{StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.StringContent, Headers:
{
  Cache-Control: no-cache
  Pragma: no-cache
  Date: Wed, 06 Sep 2017 09:33:36 GMT
  Warning: 199 RestfulObjects "Malformed arguments"
  Expires: Wed, 06 Sep 2017 09:33:36 GMT
}}
`

My action looks like this: 

`
public ResponseDto RegisterPartner(PartnerRegistrationDto dto)
{
	// do stuff here

	return new ResponseDto
	{
		Success = true,
		Message = null
	};
}
`

my angular POST looks like this:
`
$http({
	method: 'POST',
	headers: {
		'Authorization': 'Bearer ' + vm.accessToken
	},
	url: vm.Global.RestUrl + 'services/Model.Services.CommandService/actions/RegisterPartner/invoke',
	data: JSON.stringify({dto: { value : $scope.data}})
}).then(function (data) {
	console.log(data);
	if (data.Success) {
	} else {
	}
},
function (error) {
	console.error("Failed to Register", error);
});
`

**Comment by richardpawson** [comment]
Sorry  -  I can't help you debug your own code, but malformed arguments is a fairly clear message.  My suggestion would be to test your request manually i.e. access the RESTfulAPI directly using say Chrome with  a REST console plug-in, and check that if you can set up a request manually OK  - i.e. accessing a specific RESTful resource by passing the correct parameters in and getting the right response back.

**Comment by Koenyn** [comment]
I'm not asking you to debug my code, I'm asking what format should the json body be in, so that the ArgumentMap will not be empty? I really feel this is a NOF9 issue...

**Comment by richardpawson** [comment]
Have you read the Restful Objects specification?  That has the full, and very detailed, specification for the JSON body required for each RO resource.  As I said before, I suggest you test this manually and then ensure, by monitoring the request via Fiddler, say, that your programmatic call in fact has the same JSON body.

**Comment by Koenyn** [comment]
just to clarify I am specifically using a DTO and not an entity. from reading the RO documentation for a POST:
> Arguments should be formatted as a map, and sent as the body

And for how to map the arguments:

> Similarly, updating multiple properties could be done using the following
map:
{
"firstName": {
"value": "Joe"
},
"lastName": {
"value": "Bloggs"
},
"status": {
"value": {
"href": "http://~/objects/STS/NEW"
}
}
}

So how I'm formatting my DTO is as follows:

`var data = {
  dto: {
    value: {
      company: {
        value: {
          name: {
            value: 'Microsoft'
          }
        }
      }
    }
  }
}`

However looking at the NakedObjects.Rest project I see that you have ScalarValue, ListValue, 
 ReferenceValue. Which leads me to believe that the NO RO api cannot consume a standard everyday JSON DTO. Am I correct in my assumption?
if so, is there any prospect to adding support for this?

**Comment by richardpawson** [comment]
The Restful Objects specification  -  which is particular about how reference types are passed a params, and this is what the NOF RO API implements (with a small number of non-breaking custom extensions).  So you are not free to construct reference objects another way -  and there are no plans to change that.  A huge amount of work went into the RO spec -  I was heavily involved for 12 months, but the lead author was Dan Haywood  -  and we tried to use independent standards wherever these fitted what we needed it to do.  Where the RO representations look non-standard is not, I can assure you, because of arbitrary design decisions, but because we found that the state-of-the-art other standards for representations (admittedly this was 4 years ago) just were not up to the job i.e. could not provide the richness of metadata that we needed to be able to use a RESTful API to create a completely generic UI.

**Comment by brentvee** [comment]
Hey Richard,
So would RO support the following scenario  ?
```
public class PersonRepository
{
  public void Walk(MetaPerson person)
  {
  }
}
public class MetaPerson
{
  public int Id{get;set;}
}
```
where ```MetaPerson``` is a POCO/DTO that is **not** mapped to an EntityFramework entity .

**Comment by richardpawson** [comment]
That's what ViewModels are for.  So your MetaPerson would need to implement IViewModel and be created properly (see Manual if not clear).  The reason for this is that the NakedObjects server is stateless: so for any non-persistent object there must be enough information passed back with each request in order to re-create that object on the server.

**Comment by brentvee** [comment]
I've made it an ```IViewModel``` 
```
public class TestDto : IViewModel
	{
		public virtual Guid Id { get; set; }
		public  virtual string[] DeriveKeys()
		{
			return new string[]{Id.ToString()};
		}

		public virtual void PopulateUsingKeys(string[] keys)
		{
			Id = Guid.Parse(keys[0]);
		}
	}
```
but still getting the same behaviour.
I'm using Restsharp and LinqPad for testing but still getting malformed arguments. 
Can we use anonymous objects ?
My parameter looks like this 
```
request.AddJsonBody(new 
		{
			dto = new 
			{ 
				value = new 
				{ 
					Id = Guid.Parse("8F09FA77-2839-47D5-8643-B5BBCD780327") 
				} 
			} 
		});
```

**Comment by richardpawson** [comment]
I suggest you look at the Http request via e.g. Fiddler, and compare the exact form of the arguments you are sending this way, compared to the exact form of the arguments if you were retrieving the object via the generic NOF9 client.

**Comment by brentvee** [comment]
Hey Richard,
I've added a similar us case to the NOF 9 template project but can't get past the submission.
![untitled](https://user-images.githubusercontent.com/5138024/30146617-529e3c08-9399-11e7-9343-e244dd2aacdd.png)

![image](https://user-images.githubusercontent.com/5138024/30146645-7d703d00-9399-11e7-9fc1-dde92687c442.png)

**Comment by brentvee** [comment]
Ok i finally managed to perform a post
I see it needs a href on the json object pointing to the type 
http://localhost:5000/objects/Template.Model.StudentViewModel/Test

**Comment by brentvee** [comment]
I think our issue was we assumed that RO would deserialize the incoming json object to the domain type of the parameter on the domain service.

**Comment by richardpawson** [comment]
"I think our issue was we assumed that RO would deserialize the incoming json object to the domain type of the parameter on the domain service."

The reason why we can't do that is that the parameter type might be an abstract class, or an interface, where we need the concrete type of the object.  As I said earlier, though it might take you a long time to appreciate it, a lot of the seemingly arbitrary decisions taken in designing the RO spec was based on our 15 years experience of developing the concept of a generic OO UI.

Anyway, I'm glad you got it sorted.

**Comment by brentvee** [comment]
One last question.
What happens if we have a very complex viewmodel that has nested objects etc.
In our current use case we have a large customer registration view model that looks something like 
```
public class RegistrationData : IViewModel
{
  public virtual string Name{get;set;}
  public virtual ICollection<Vehicles> Vehicles{get;set;}
  public virtual ICollection<Drivers> Drivers{get;set;}
  public virtual string[] DeriveKeys()
  {
	// derive
  }

  public virtual void PopulateUsingKeys(string[] keys)
  {
     // populate
  }
}
```
All of this information would be new so not available to read from a datastore. So we would need to repopulate this viewmodel from all the keys.
But the keys are now all strings, so how would this work for the ```Vehicles``` and ```Drivers``` collections?

**Comment by richardpawson** [comment]
I have to say that, to my eyes, this is not the way to operate.  The idea of a user filling in pages of repeating-structure data and none of it being persisted until it is all submitted in one go, is just not the way I would design a system  -  it leaves the user very vulnerable to events that would cause all their temporary data on the client to be lost.  I would be saving it as the user entered it, one object (e.g. Vehicle, Driver) at a time.  It could be persisted with a 'provisional' status until the entire set was deemed complete, and then transitioned from provisional to confirmed in one go.

**Comment by brentvee** [comment]
I agree that the form is rather large but we have a very extensive client side capturing process that gathers lot of information from different sources as the user progresses through it.
This is all finally saved as a single transaction and a single payload to the server.
Do you not think RO is the way to go for this particular use case ?

**Comment by brentvee** [comment]
I think what I'm try to ask is, would this solution with passing around keys work, even for a small viewmodel that requires some relationship 
```
public class StudentViewModel
{
	public string Name{get;set;}
	public TeacherViewModel Teacher{get;set;}
}
public class TeacherViewModel
{
	public string Name{get;set;}
}
```

**Comment by richardpawson** [comment]
It would work -  including both the student's name and teacher's name as keys -  though you'd then have to re-create the TeacherViewModel in the PopulateUsingKeys method.  But this would not be commonplace, and nor would I recommend it. More commonly a view model would have been create from one or more persistent objects in the first place, and may well contain collections of associated _persistent_ objects, which is easy.  The idea of using a VM for inputting a complex graph of objects created on the client is, to my mind, antithetical to the whole Naked Objects way of thinking.  It means you have:

1. Created a highly custom UI
2. Are holding a whole graph of user-entered objects in the client with no back-up until the user has completed the entire transaction.

As said, I would urge persisting the objects (albeit with a status of, say, Pending) as they are entered, making use of the MultiLineDialog capability that we introduced in NOF8.  

Alternatively, just upload the graph of data as a blob (i.e. making use of the equivalent functionality to the File Upload on the NOF9 UI, and then turn it into persistent objects inside a server method.

**Comment by brentvee** [comment]
Thanks for all the assistance Richard
