### ISSUE TITLE
Nof 7 Errors when using the word 'action' as a parameter name

### ISSUE THREAD

**Issue by brentvee** [NakedObjectsGroup/NakedObjectsFramework#98]
Hey Richard,
Just found a strange issue in NOF 7 when using the word ```action``` as the name of a parameter. 
Example
```public void Do(int action)```
There's a weird javasript error that occurs
```TypeError: $.address is undefined```

**Comment by richardpawson** [comment]
I have never stumbled across this before, but after testing it appears to be the case even for the latest NOF9, which yields this error message, giving some insight into the issue:

`Message: The UriTemplate 'services/{oid}/actions/{action}/invoke?action={action}' is not valid; the UriTemplate variable named 'action' appears multiple times in the template. Note that UriTemplate variable names are case-insensitive. See the documentation for UriTemplate for more details.`

However, I discovered that it is possible to work around this (at least in NOF9  -  I haven't tried it for NOF7) by renaming the parameter e.g.:

`public void Foo([Named("Action")] int bar)`

I will document this singularity, and the workaround, in the NOF Manual  -  given the source of the issue it would probably not be practicable to eliminate it.

**Comment by brentvee** [comment]
Ok, thanks Richard
