### ISSUE TITLE
simple file attachment sample in manual does not work

### ISSUE THREAD

**Issue by smiltenburg** [NakedObjectsGroup/NakedObjectsFramework#99]
I'm having trouble migrating the file attachment functionality from my NOF7 app so I tried to start from scratch with the basics and I noticed that the basic implementation mentioned in the manual does not work because there is no browse button rendered in the ui to select a file

public virtual byte[] Attachment { get; set; }

public void AddOrChangeAttachment(byte[] newAttachment) {
  Attachment = newAttachment;
}

**Comment by smiltenburg** [comment]
to be clear I am not using this functionality (i'm using the fileattachment approach) but I just wanted to let you know that the manual is probably out of date for this issue. 
The fileattachment implementation seems to be better in many ways so maybe just drop this "basic" functionality from the manual?

**Comment by richardpawson** [comment]
I have now updated the documentation.  In NOF9 you must use the FileAttachment type  -  a simple byte array will not be recognised.
